### ISSUE TITLE
Too many config files

### ISSUE THREAD

**Issue by Ellmen** [electron-react-boilerplate/electron-react-boilerplate#1573]
Including configs for things like flow, vscode, and travis adds a lot of mess to clean up for people who don't use those things. Since this is *the* react electron repo, I feel like it should be stripped down a little.

**Comment by amilajack** [comment]
Which configs should we get rid of?

**Comment by aguynamedben** [comment]
Just registering another opinion... I think the flow configs are good because they provide an opinionated best practice, which is what boilerplate is for.

I think the editor-specific configs could either be removed (because everybody uses a different editor, and your choise editor isn't necessarily related to the project ecosystem), or it should be an explicit policy that other editor configs are welcomed and maybe put them in editor_configs/ with a README file in that directory explaining the policy. I use Emacs, but VS Code seems to be an emerging norm in the JS community so it's probably helpful to have a config laying around.

Also, wouldn't removing yarn.lock make it pretty difficult to debug issues people are having with the project? yarn.lock in projects I've worked on is always committed to make sure that people are using the same dependencies without having to continually ask everybody to list which version they have installed locally.

In general my opinion is:
* It's not that hard to remove config files, and they rarely get in the way. You're going to have to customize this repo for your project anyways. `git rm`ing or editing a few config files you don't find helpful is much easier than being a newbie and not having access to sensible config files. For example, being new to the whole ecosystem it would be very hard to create a Flow config from scratch.
* The purpose of boilerplate is to help people get going in an ecosystem quickly.
* Example config files, even if they're not setup out of the box the way you'd like, are very helpful as it's difficult to come up with from scratch when you're new to an ecosystem.
* Config files are a good opportunity to set opinionated best practices, which is especially useful in boilerplate projects. These best practices reflect norms in a community.

Boilerplate seems like the BEST place for config files. The cost of removing/modifying config to fit your preferences is much lower than the cost of not having ready access to example configs.

**Comment by Ellmen** [comment]
1. I like the idea of an editor_configs and I can appreciate that having sample code makes it easier for a newcomer to get started.

2. The main yarn.lock is certainly important - the one I was talking about is in the app directory and is empty (there are no dependencies in that directory's package.json)

3. I would argue that Flow isn't actually a best practice and integrating it so deeply makes this project less flexible. Skype, GitHub, and Slack are all using TypeScript. The problem with enforcing a certain stack is that when any part of it becomes obsolete, the whole project does.

It kind of depends on if this project is supposed to be a pure electron-react boilerplate or if it's a "cool stack" that runs on electron and react. Personally, I was just looking for a clean way to structure an application that uses the two technologies.

**Comment by aguynamedben** [comment]
Cool, those opinions make sense too.

I'm just curious for my own education, are you using this repo with TypeScript? I've just been using Flow since it was already in this project... but I'm not partial to it. Was it easy to get TypeScript working with this?

Whether this project is best as "cool stack" or "basic stack", I could see a change from Flow to TypeScript being a reasonable opinionated change. Coming from non-JavaScript land, there are already a lot of other opinions built-in (Webpack, ES6, testing framework, Redux).

I'd like to see "cool stack". I'm a Rails fan and have seen the "cool stack" decision go the undesirable way (i.e. CoffeeScript), but overall I like things to be opinionated and bundled (Rails for Ruby) vs. piece-together-your-own-together (i.e. Flask for Python). Just opinions though. Good discussion.

**Comment by ManuKle** [comment]
You can find my typescript fork under [notable forks](https://github.com/chentsulin/electron-react-boilerplate/wiki/Notable-Forks) in the wiki. It's based on version 13.3 and I'll try to update soon with the latest commits.

Regarding the configs, I kinda like the idea of putting them in a separate folder. But I wouldn't delete them, as they are useful to build upon.

**Comment by aguynamedben** [comment]
@ManuKle very cool!

**Comment by vikr01** [comment]
In #1686, we moved `webpack` configs to a `configs` folder. That drops quite a few files from the home directory.
