### ISSUE TITLE
Migrate to babel@7

### ISSUE THREAD

**Issue by amilajack** [electron-react-boilerplate/electron-react-boilerplate#1734]

**Comment by vikr01** [comment]
Been working on it at [/vikr01/electron-react-boilerplate/tree/feature/babel-7](/vikr01/electron-react-boilerplate/tree/feature/babel-7).

When running commands from the root directory, everything works fine. When running from the `app` directory, babel is not finding its config.
Issue seems to be related to babel believing the project is a monorepo due to `app/package.json`. [Switched `.babelrc` to `babel.config.js`](https://babeljs.io/docs/en/config-files#project-wide-configuration) and still no luck.
