### ISSUE TITLE
Should the project move away from the 2 package.json structure?

### ISSUE THREAD

**Issue by aguynamedben** [electron-react-boilerplate/electron-react-boilerplate#1827]
I recently asked a question in electron-rebuild (used by this project as well as electron-builder) and was told by an experienced Electron community member that it's a bad idea to use the 2 package.json structure with electron-rebuild.

https://github.com/electron/electron-rebuild/issues/253#issuecomment-426833695

I was wondering if you've considered moving away from the 2 package.json structure? It seems that since version 8, electron-builder is smarter about how it rebuilds native dependencies...

From https://www.electron.build/tutorials/two-package-structure
> Since version 8 electron-builder rebuilds only production dependencies, so, you are not forced to use two package.json structure.

I'm not an expert in this area, but happy to help if this sounds like a good idea.

About my project if it helps understand my context:
* Based on electron-react-boilerplate
* Uses the 2 package.json structure
* Needed to modify ElectronRebuild.js to use electron-rebuild's `--which-module` because I need to exclude `node-sqlite3` from my electron-rebuild command because I need to build `node-sqlite3` from source so that I can [use SQLCipher encryption for SQLite](https://github.com/mapbox/node-sqlite3#building-for-sqlcipher).
* [My current ElectronRebuild.js](https://gist.github.com/aguynamedben/93f742a513fd283b28e4e44bb1cea66d). I use electron-rebuild to rebuild all modules except for node-sqlite3. After rebuilding other modules, I compile node-sqlite3 from source with SQLCipher support.

**Comment by vikr01** [comment]
The 2 `package.json` structure definitely needs to go, if it's possible.

Modules generally see the `package.json` as the root of the project. There are issues upgrading `babel` because of this structure and it thinking the whole project is a monorepo.

**Comment by aguynamedben** [comment]
I'm no expert, but I think going to a modern single package.json structure might require getting rid of Webpack.

From https://github.com/chentsulin/electron-react-boilerplate/wiki/Module-Structure----Two-package.json-Structure#webpack-and-native-dependencies
> Webpack has issues with bundling native dependencies. This may have to do with some modules having dynamic require statements.
I'm not sure the root cause is known.

The "Why use Webpack at all?" section has this:
> Electron apps face massive obstacles when it comes to matching native performance.
and mentions slow startup times (due to run-time `require()`'s being slow).

I think the `require()` startup time issue his has been addressed by the Atom team by releasing electron-link. This is a very important read: http://blog.atom.io/2017/04/18/improving-startup-time.html So, the main primary reason for using Webpack in the first place might now be outdated. I'm not sure. I know for my app I wouldn't mind if startup was slightly slower if it saved me dev cycles and reduced complexity.

To me, the complexity of Webpack isn't worth it. I need to figure out how to eject Webpack + two package.json structure from my project. It seems like major apps (Slack, Atom) are built without Webpack, and they decide that the tradeoff of doing run-time `require()`s is worth the reduced complexity.

I'm happy to be corrected, I'm just trying to coalesce what I'm seeing in the community and get feedback. Webpack's overwriting of `require()` also breaks important Node & Electron dependencies (i.e. umzug, electron-userland/electron-remote) that expect to see Node's `require()` and instead get Webpack's `require()`.

Here are the tradeoff from what I've learned building a project from this boilerplate for a year. To me, there are 2 types of Electron apps. Webpack and non-Webpack.

Webpack (+ two package.json structure)
* Precompiles your code (i.e. to app/main.prod.js, app/renderer.prod.js) before shipping it to your user.
* Webpack usage overwrites Node's `require()` with the Webpack `require()`. This breaks dependencies that aren't careful to tiptoe around Webpack (umzug, electron-userland/electron-remote).

Straight Node.js with Electron
* Seems to be the pattern most Electron experts advocate. Uses conventions that Slack and Atom use (not sure about Spotify, haven't looked).
* You ship runnable Node code to the user (un-ASAR the Slack app to witness this). Their machine runs the Node code as written, instead of code precompiled by Webpack. The user is running your app as it's written.
* `require()` can slow app startup, but that can be addressed using electron-link as documented in the Atom startup performance blog post.

Thanks for the time everybody has put into this project. The Electron community seems a bit dispersed, that's why I'm trying to summarize my perspective here. Hopefully it leads to a good discussion.

**Comment by HyperSprite** [comment]
@aguynamedben - Wait a minute..., I've been working on adding migrations to my projects sqlite/sequelize db, and was here because of the dreaded **'Please install sqlite3 package manually'** trying to use `sequelize-auto-migrations` are you telling me the **umzug** is also going to fail?

**Comment by aguynamedben** [comment]
@HyperSprite From what I remember of trying to use Umzug, the issue I ran into is that umzug calls require() to include migration files. Umzug expect to get Node's `require()`, but instead it gets Webpack's `require()` (Webpack overrides `require()` with it's own voodoo).

I believe the root cause is documented here: https://github.com/webpack/webpack/issues/1554#issuecomment-158679844

Webpack overloads Node's `require()` as part of it's "tree shaking" and package building.

I haven't yet looked at Rollup yet, but my instinct is to just not use any pre-compiling and go straight with Node.js. If you decompile (i.e. un-ASAR) the Slack app, you can see that it starts up by simply running something like `node -r babel-register start.js`. It just runs the script on the user's computer. The downside is that all the `require()`s have to happen at run-time, but the Atom article I mention mitigates slow startup times. And for me personally, my app doesn't get restarted that much, so I care very little about a non-optimal startup time.

@HyperSprite I'm in San Francisco and also building a real product branched from 0.12/0.13. If you want to meet up and sort this out I'd be happy to work with you on finding a solution. I think I know generally what to do, I just haven't prioritized it (vs. product features).

**Comment by HyperSprite** [comment]
Well, that was a whole weekend... 

### Rollup

First I tried Rollup... just to see if it made sense. Had I been starting with a fresh project, that might have worked out but it was literally one error after another regarding how things were imported. Wasted a whole day and could not eve get it to start. 

### Flattening package.json 

Sunday I went back to Webpack and was able to flatten the project to one `package.json` file. It's not all that hard to do but does have some tradeoffs. 

* Native packages (and the ones that require those packages it seems) need to be added to webpack externals. The current two package setup does this automatically. I created an `"externals: [<strings>]"` in the root package.json and import it into webpack.config.base for externals.
* The built package uses the root package.json for the version number. I kind of liked having them seperate so I could track the boilerplate and app separately. I did not see an override for this for electron-boulder but there is a build number addition that could be used.
* It does simplify package additions though, so that's a plus.
* I have not had a chance to test everything, but currently I am able to run my DB tests without the @jest-runner/electron which for me is a huge win because it leaves open electron processes. I won't know for sure until I clean my node_modules and remove the package though, just to make sure.
* Less places to keep track of the name of the app.


### Is this right for ERB? 
If this sounds interesting for the ERB project, _maybe others want to weigh in_. I could apply my changes to a clean fork as a demo / pr. (Might take me a few days, I'm trying to catch up for some lost time last week)


### Meanwhile...

#### ...and I don't mean to go off topic but at the same time, none of that fixed my issues with Sequelize and Umzug

Both projects are super opinionated about where and how they think they are running. My guess is running on some node server with a database that is connected to at startup and left connected. So pulling in model and migration files from folders in the app root at runtime is no big deal. 

My app, on the other hand, needs to create new / open existing dbs on the fly and migrate them if necessary, treat it more like a document than a long running database connection.

What I think is really going on is the way that Sequelize and Umzug pull the files in using `fs.readdirSync()` to walk the directory **at run time**. Webpack has no idea what this code is for and since they are not imports/require, it just ignores them. My previous setup had hard imports for each model but that was not going to work with dynamic migrations so I had to refactor.

So here is what I came up with, and take this with a grain of salt, I just came to last night so I've not had time to run through all the sceneries but it seems to be working. My tests are passing, builds work on Window and Linux but there's more things I need to check.

* Move `models` and `migrations` folder in root of project (outside of app, mine were living in app/db/models, migrations)
* yarn add --dev copy-webpack-plugin
* In webpack.config.base.js

```js
// import it
import CopyWebpackPlugin from 'copy-webpack-plugin';

// blah blah webpack stuff
// then go to the bottom and add the plugin

  plugins: [
    new webpack.EnvironmentPlugin({
      NODE_ENV: 'production',
    }),

    new webpack.NamedModulesPlugin(),

  // added this part from here
  // the 'to' is already prepended with app/dist 
    new CopyWebpackPlugin([
      { from: 'models', to: path.join(__dirname, 'app', 'dist', 'models') },
      { from: 'migrations', to: path.join(__dirname, 'app', 'dist', 'migrations') },
    ]),

  // to here
  ],
```

* Some dev/prod logic for locating files
 * **dev** uses the root { models, migration } folders
 * **prod** uses app/dist/{models, migrations} folders. 

lib.js file imported by both files is exporting this
```js
// feels ugly but reliable :/
const rootOrDistDir = () => {
  if (process.env.NODE_ENV !== 'production') {
    return path.join(__dirname, '..', '..', '..')
  }
  return path.join(__dirname, 'dist');
}
```

connection.js : db connection manager
```js
const modelsDir = path.join(rootOrDistDir(), 'models');
// standard model inclusion for Sequelize cli
fs.readdirSync(modelsDir) // rest of file …
```

migrations.js : umzug runner file
```js
const migrationDir = pathJoin(rootOrDistDir(), 'migrations');
// rest of file… 
```

For reference, my new file structure is this:
```bash
| app
|  | client
|  | db
|  |   | connection.js    # handles db connection and model traversal
|  |   \ migration.js     # typical umzug config
|  | dist
|   \ main.dev.js
| migrations
|   \ all migration files
| models
|   \ all model files
| webpack.config.base.js
| # everything else
```

@aguynamedben I may have sorted out my issues but it would still be nice grab some coffee with someone working from the same boilerplate. I'll shoot you an email.

**Comment by HyperSprite** [comment]
After more testing with SQLite/Sequelize I am convinced a single package.json is really the only way to run that setup. So I had a little time to look at this today and put together a forked example. 

I removed the `electron-rebuild` package since the same things can be accomplished with `electron-builder install-app-deps` in postinstall. I also removed `CheckNativeDeps`.

Build now looks like this:
```json
"build": {
    "productName": "ElectronReact",
    "appId": "org.develar.ElectronReact",
    "files": [
      "app/dist/",
      "app/app.html",
      "app/main.prod.js",
      "app/main.prod.js.map",
      "package.json"
    ],
 "//": "all the other stuff"
```

## Webpack Externals

The [webpack wiki](https://github.com/webpack/docs/wiki/library-and-externals) describes externals like this:

> `externals` allows you to specify dependencies for your library that are not resolved by webpack, but become dependencies of the output. This means they are imported from the environment during runtime. 

### Currently 
The 2 package system sets all of the app/package.json dependencies to externals then uses the `filterDepWithoutEntryPoints()` to create externals for certain packages.

I've tested and run this two ways and they both work.
1. Create an array of package names for externals and add that to the webpack config and keep using the filterDepWithoutEntryPoints().
2. Just make all dependencies externals by removing the filter and just adding all production dependencies as externals.

Option 1 works but it needs each developer to maintain the `externals` array in the package.json for their particular project and if something is left out, there are errors.

Option 2 just works, no configuration.

#### Size

Build size of Option 1 is 1mb larger than Option 2
The node_modules folder in the app.asar is exactly the same size.

##### exe
Option 1 = 54.2mb vs Option 2 = 53.2mb 

##### Appimage

Option 1 = 73.7mb vs Option 2 = 73.0mb

#### E2E test (I'm still on Spectron but it's quite elaborate)
Option 1 runs .035 s faster than Option 2, so negligible. 

From a simplicity standpoint, Option 2 is probably the best because it will reduce a whole slew of errors and issues stemming from native dependencies. 

### So my question is what is the downside to going with Option 2?

**Comment by HyperSprite** [comment]
Ok, here it is using Option 2: 
https://github.com/HyperSprite/electron-react-boilerplate/tree/single-package-setup

I'm on linux and was able to pass tests and build all the linux installers and the nsis installer but could not build an msi installer. I did not test Mac. 

Minimal changes, should be a drop in replacement for most people.

**Comment by vikr01** [comment]
@HyperSprite This looks great, would love a PR.

My only issue is that `moduleDirectories` is still specified for `jest`. Is that still necessary without the 2 `package.json` structure?

The reason I say that is because one of the biggest issues with the 2 `package.json` structure is that `yarn` is evolving with `workspaces` and `plug'n'play` and `node_modules` should not be expected to be in a certain place anymore. They can be hoisted. With ERB endorsing the use of `yarn`, we need to be able to support these features.

**Comment by HyperSprite** [comment]
@vikr01 - I just ran tests **with** and **without** `jest` > `moduleDirectories` in the package.json and it passes either way.
```bash
11:25 $ yarn run test
yarn run v1.9.4
$ cross-env NODE_ENV=test BABEL_DISABLE_CACHE=1 node --trace-warnings -r babel-register ./internals/scripts/RunTests.js
 PASS  test/reducers/counter.spec.js
 PASS  test/actions/counter.spec.js
 PASS  test/components/Counter.spec.js
 PASS  test/containers/CounterPage.spec.js
```

I can't run the E2E test right now. I'm still using Spectron in my project and not setup for TestCafe on my box yet.

If that's all good, I could probably do a PR later today.

**Comment by vikr01** [comment]
@HyperSprite after looking into it, seems `jest` by default sets `moduleDirectories` to `node_modules` so it's probably okay to keep.

Also, is [`resolve.modules`](https://github.com/HyperSprite/electron-react-boilerplate/commit/85606e5d3028e87ae8ea68d85fb3517bf262da89#diff-b18e48f625568f8d54a06d1b42702ce3R38) still needed in `webpack`? As in, if a module was to be installed in an upper directory, would it cause the build to break?

**Comment by vikr01** [comment]
Related: #1754 #1689 #1763.

**Comment by HyperSprite** [comment]
@vikr01, man, good catch on the `resolved.modules`, there are so many nooks and crannies. For instance, I just noticed this a few minutes ago. https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/.eslintrc#L73

`"config": "webpack.config.eslint.js"` should be `"config": "configs/webpack.config.eslint.js"`

But I'm off in the weeds on another issue an have not had time to do anything about it. 

Yeah, I don't think that is needed either. I'll try taking it out and rerunning all of the tests. Definitely trying to get a pull request in today.

On a side note, I noticed this #1853 and am concerned. I've never run `yarn run start`, I'm either using `yarn run dev` or `yarn run package-xxx` and testing built code on windows and linux. Should `yarn run start` work? For me it looks like it is getting transpiled but then failing on the first import in `main.prod.js`, perhaps it is still pointing at `main.dev.js`, not sure, I haven't looked at it closely and did not want to spin cycles if this is just some remnant. 

If it should work, I've got to do more investigation and testing before I can submit the pull request.

**Comment by HyperSprite** [comment]
@vikr01 I have not updated all dependencies, only the ones that seemed to have issues because I didn't want to get bogged down troubleshooting module upgrade issues. 

Or should I just submit the pull request with what is up there now?

Sorry, I'm new here, just want to make sure I'm not wasting peoples time.

**Comment by vikr01** [comment]
sure sounds good @HyperSprite

**Comment by HyperSprite** [comment]
So I did a little work over the weekend and was able to move my existing v0.14 ERB project to this single package setup without too much difficulty. It felt a lot less tedious than when I went from 13 to 14.

I updated my pull request with the changes mentioned above. 

* remove none_modules from jest config 
* fix the .eslint loader/resolver path
