### ISSUE TITLE
How to disable hot reload in dev?

### ISSUE THREAD

**Issue by janmisek1** [electron-react-boilerplate/electron-react-boilerplate#1860]
## Prerequisites

- [x] Using yarn
- [X] Using an up-to-date master branch
- [] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [] Link to stacktrace in a Gist (for bugs)
- [] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior
Hello,

How to diseable hot reload in dev? `$ START_MINIMIZED=true yarn dev` not work for me.

Thanks

- Node version : v10.10.0
- Operating System and version : Ubuntu 18.04.1 LTS

**Comment by Slapbox** [comment]
Not sure what the default setting is, but either comment out or set to false on this line:

https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/configs/webpack.config.renderer.dev.js#L256

**Comment by janmisek1** [comment]
@Slapbox :

Thanks, 
I have tried this, but its not works. I have tried commnted or deleted everything with word "hot" but it does not help.

**Comment by Slapbox** [comment]
Not 100% sure how it works since it's been a while since I tinkered, but have you tried removing these lines?

https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/configs/webpack.config.renderer.dev.js#L51

https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/configs/webpack.config.renderer.dev.js#L75

_____

If that doesn't help, try commenting out all of this:

https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/app/index.js#L17-L27

**Comment by vikr01** [comment]
Closing since question has been answered.
