### ISSUE TITLE
Why use yarn instead of npm?

### ISSUE THREAD

**Issue by gorilla-devs** [electron-react-boilerplate/electron-react-boilerplate#1887]
Why did you choose to use yarn instead of npm? I see no real advantage in using yarn, it's just an added layer of complexity in an already complex project.

**Comment by vikr01** [comment]
`yarn` has some features that `npm` doesn't, such as [module aliasing](https://yarnpkg.com/lang/en/docs/cli/add/#toc-yarn-add-alias), [`workspaces`](https://yarnpkg.com/lang/en/docs/workspaces/), and [`plug'n'play`](https://github.com/yarnpkg/pnp-sample-app). While we're not using any of those features right now, we might in the future.

The collaborators use `yarn` and our CI's use `yarn` as well, so we recommend `yarn` over `npm` to avoid compatibility problems.

There is nothing stopping anyone from using `npm` over `yarn` in their projects, but if they do that and they end up running into bugs because of it, we probably won't be able to help them.

**Comment by gorilla-devs** [comment]
Do you see any performance improvement on using yarn over npm?

**Comment by amilajack** [comment]
We chose to go with yarn for the features if offers rather than performance, as @vikr01 mentioned. I haven't noticed much of a difference in performance. I think @vikr01 answered this well so i'll close this
