### ISSUE TITLE
How do I remove react-router, flowtype, eslint and jest?

### ISSUE THREAD

**Issue by ShadyThGod** [electron-react-boilerplate/electron-react-boilerplate#2097]
<!-- 
  Is this a bug report?
  If so, go back and select the "Bug report" option or your issue WILL be closed.
--!>

Since I'm not going to use any of the above-mentioned dependencies in my app, how do I get rid of them? I only require webpack, react, redux and hot module reloading.

**Comment by amilajack** [comment]
It would take a significant amount of time on our end to document every combination of infra that people would like to use and no use. Also eslint and jest are key pieces of infra in the JS ecosystem so I don't recommend removing them. It may seem like we're using a lot of infra but because electron-react-boilerplate's goal is to provide a foundation for scalable cross-platform apps and that requires infra.
