### ISSUE TITLE
Documentation for upgrades

### ISSUE THREAD

**Issue by jp887** [electron-react-boilerplate/electron-react-boilerplate#2132]
I have been unable to find any documentation around upgrading projects between versions of the boilerplate. The [upgrade documentation](https://electron-react-boilerplate.js.org/docs/upgrade-guide) don't seem to contain much.

Am I correct in assuming that after cloning the repo the intention is that users of this project should add an upstream remote pointing back to this repo in order to merge in changes?

If someone with more experience of performing upgrades is able to confirm the recommended upgrade path/instructions then I'd be happy to submit a PR to add some more documentation if that is useful?

**Comment by aguynamedben** [comment]
Just to give you a sense of how we've been thinking of this... here's my experience of building a serious project on top of this boilerplate, which has been overall a success that's made me very grateful for the boilerplate.

* About a year ago I started a project based on the boilerplate.
* Built a ton of stuff in the first 3-6 months.
* About 6 months in I merged a new release of the boilerplate into my project. There was a lot to merge because both projects (my project and the boilerplate) each had so many changes.
* My project got really big (lots of features) and the boilerplate moves very fast (not many features in the app itself). At this point it's unrealistic to merge boilerplate changes into my project. There are just too many changes on both sides. Sometimes I'll copy Webpack snippets, use ideas, or alter my directory structure to mirror the boilerplate, but it's always manually, not via a merge.
* I subscribe to change in the repo and get an email for every Issue and Pull Request. I read these emails pretty carefully to see if there are any changes/questions that apply to my project. At this point the boilerplate is most valuable to me as a community forum for latest best practices (with code attached!) Sometimes if I'm getting frustrated by Webpack or another feature, I'll clone the boilerplate and try it out in the boilerplate. This usually gives me a good sense for if something is going on in my app's logic (i.e. works in the boilerplate fine!) or with configuration (this also breaks in the boilerplate, maybe I need to tweak Webpack, babel, Electron version, etc.).

Keep in mind this is a boilerplate (example project) not a framework (code to build your app on). The boilerplate remains extremely valuable. Just be realistic about your project progressing and your ability to continually merge the boilerplate changes into your project. They will diverge pretty quickly.

**Comment by jp887** [comment]
@aguynamedben thank you for sharing your experience, this is really useful information. What you say makes perfect sense. On reflection I was probably thinking about this with too much of a framework mindset. What you have said has answered my question so I'm closing the issue. 

I do wonder if there might be some value in adding a sentence or two somewhere in the docs to articulate this point. I guess the fact that there is an upgrade section but that it is almost empty lead me to assume that the docs were incomplete rather than that upgrading directly is not likely to be a routine task when building from the boilerplate.

**Comment by aguynamedben** [comment]
Yeah, I'm no authority on this project, just sharing my experience. I do think it'd be helpful to have some sort of "So you're going to use this for a serious project?" section in the docs that gives some direction from the maintainers of this project on what they can expect if they're going to start using this for something serious vs. just learning.

**Comment by amilajack** [comment]
@aguynamedben can you give some examples of what maintainers should include so i can get a better idea of what you mean. This sounds like a good idea. I think the docs are very lacking now. Mostly because they take a lot of time and i'm not sure what parts of ERB people would like to be documented. Can you also share some ideas on how to improve the docs? Thanks!

**Comment by aguynamedben** [comment]
Maybe an opening paragraph for the [Upgrade Guide](https://electron-react-boilerplate.js.org/docs/upgrade-guide). Feel free to edit, change, cherry-pick what you like, etc.

---

This project moves pretty quickly and demonstrates cutting edge JavaScript+Electron+React best practices. People often ask how to keep their app updated with the changes from the boilerplate (see [discussion](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2132)). Keep in mind that this is a boilerplate project with a purposefully tiny feature set (a counter). The boilerplate will enable you to build an advanced app with a large feature set, and over time your advanced app will diverge from the simple feature set of the boilerplate. Hopefully this boilerplate helps keep you educated about the quickly evolving best practices for JavaScript+Electron+React.

#### Tips for keeping your app modernized
* Track human explanations of the changes between versions in this [Upgrade Guide](https://electron-react-boilerplate.js.org/docs/upgrade-guide). We've started typing readable summaries of the major changes in each release.
* Try merging new releases into your project, especially early on, but expect your project to evolve beyond the boilerplate and for merging upstream changes into your project to become untenable.
* Subscribe to changes from this repo. Even if you can't merge every change into your project, watching changes from this repo will help ensure you don't miss major changes, and help you appreciate the smaller ones.
* If something breaks in your advanced app, try it in the boilerplate. Seeing if something works in the boilerplate can help you understand if it's a configuration issue inherited by the boilerplate or something you broke on your own. This is especially relevant for building native modules, Webpack config changes, babel config changes, additional renderer processes, etc.
* Be realistic about what this project gives you. The boilerplate is meant to be a working educational example. It's a demonstration, not a black-box development framework for you to build on top of. Inspect the boilerplate, understand how it works, and tweak your app to meet your needs.

**Comment by amilajack** [comment]
Thanks for this! I just [added your suggests with some modifications](https://electron-react-boilerplate.js.org/docs/upgrade-guide#ugrading-to-0170-from-0160). Also we've recently made a distinction between ["community docs" and "official docs"](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki). The plan with this is that community docs that are added to our official docs. The idea behind this distinction is that anyone can quickly update community docs. Officially docs are reviewed and can only be published by maintainers. Good community docs will be migrated to the official docs. Just an FYI on the changes

**Comment by aguynamedben** [comment]
Cool, thanks for the hard work you put into this project. 🙏
