### ISSUE TITLE
Compiled apps use development version of react and react-dom

### ISSUE THREAD

**Issue by Kilian** [electron-react-boilerplate/electron-react-boilerplate#2148]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior
An app created with `yarn package` will use `react.production.min.js` and `react-dom.production.min.js`

## Current Behavior

An app created with `yarn package`, in vanilla git clone's of both the master and the next branch, ships with `react.development.js` and `react-dom.development.js`, see screenshot below.

<img width="1640" alt="screenshot 2019-02-07 at 23 07 38" src="https://user-images.githubusercontent.com/41970/52446082-46089100-2b2d-11e9-901c-a10ea3bd6ac3.png">

## Possible Solution
Not found any yet, but I assume NODE_ENV gets overwritten or unset somewhere.

## Steps to Reproduce (for bugs)

1. fresh checkout of the repo
2. `yarn` 
3. `yarn run package`
4. inspect the sources of the app

## Context

A compiled app should be as fast as possible, running the production version of react is very important in that context.

## Your Environment

- Node version : 10
- Version or Branch used : master as well as next
- Operating System and version : mac os mojave

**Comment by Kilian** [comment]
I just tested this out on Ubuntu and there it's also using the development version instead of the production version.

**Comment by barretron** [comment]
It looks like there was a change while migrating to the single `package.json` structure that externalizes *all* dependencies from the webpack bundle:

Note these lines in `configs/webpack.config.base.js`:
```js
import { dependencies } from '../package.json';

export default {
  externals: [...Object.keys(dependencies || {})],
```
One workaround would be to manually specify any native deps (and maybe also ones that webpack complains about) e.g.:

```js
  externals: ['electron-debug'],
```

There might also a decent way to figure out if a given dependency is a native dep, but I'm not sure. Best I can think of is to `grep` through `node_modules/**/package.json` for `node-gyp`.

**Comment by amilajack** [comment]
I have confirmed this bug as well. I think this has to do with the https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/1854

**Comment by barretron** [comment]
It looks like the production versions of React are being used. A combination of `react-dom` and the React DevTools are throwing this error due to the faulty assumption that `process.env.NODE_ENV` is always statically replaced in a browser context (i.e. through webpack).

See the `checkDCE` function here [react-dom/npm/index.js](https://github.com/facebook/react/blob/baff5cc2f69d30589a5dc65b089e47765437294b/packages/react-dom/npm/index.js)

And how React DevTools uses `Function.prototype.toString` to verify that DCE removed the unreachable code: [backend/installGlobalHook.js](https://github.com/facebook/react-devtools/blob/faa4b630a8c055d5ab4ff51536f1e92604d5c09c/backend/installGlobalHook.js#L129-L154)

**Comment by Kilian** [comment]
Verifying that the packaged app is still using the development bundle can be done by adding some code that triggers a warning. Warnings are shown by the react development bundle but are suppressed by the production bundle. 

An easy way to get a warning is to add an illegal but syntactically correct bit of JSX, like a button nested inside a button:
```
        <button>
          <button>This is a button in a button!</button>
        </button>
```

When you do this and run `yarn run dev`, you will get a warning: `Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.` This warning should disappear when opening the package app, but it is not:
<img width="1025" alt="screenshot 2019-02-10 at 13 12 08" src="https://user-images.githubusercontent.com/41970/52533550-82a6d900-2d35-11e9-9069-c2cd580b567c.png">

**Comment by barretron** [comment]
I can reproduce it using @Kilian 's test after running `yarn package` (I was using `yarn start` before, which doesn't package the app).

Here's what seems to work for me so far:

Add the following snippet to `plugins` in the prod webpack configs:

- `configs/webpack.config.main.prod.babel.js`
- `configs/webpack.config.renderer.prod.babel.js`

```js
    /**
     * Set NODE_ENV to "production" for external dependencies
     *
     * Note: this is required for both main and renderer
     * separately since the renderer process doesn't inherit
     * the main process's environment on Linux.
     */
    new webpack.BannerPlugin({
      banner: 'process.env.NODE_ENV="production";',
      raw: true,
      entryOnly: true,
      test: /\.js$/
    })
```

🤷‍♂️ kind of hacky but guarantees that the environment will be set prior to any `require` statements running

**Comment by Kilian** [comment]
`yarn start` runs electron with `NODE_ENV=production` prefixes, which is why that does work (though there is a comment there on lacking dead code elimination?)

Thanks for the plugin above! It's not ideal but it gets the job done! :+1:

**Comment by clytras** [comment]
Any progress or workaround with this one?

![image](https://user-images.githubusercontent.com/6103077/54535253-d214a080-4996-11e9-84c4-59200022079e.png)

> React is running in production mode, but dead code elimination has not been applied.

I think this is releated to `TerserPlugin` configuration for production.

**Comment by Puritanic** [comment]
Hi, is anyone resolved this somehow? I'm receiving the blank page in the built prod version of the app, as well as `Uncaught Error: React is running in production mode, but dead code elimination has not been applied.` error...

Not sure what's happening, it was working fine a few days ago and stopped working today.

**Comment by barretron** [comment]
After running into additional problems with libraries assuming a minified browser environment, I ended up just bundling all libraries with `webpack` again rather than importing them directly from `node_modules`:

**configs/webpack.config.base.js**

1. Remove the line
    ```js 
       import { dependencies } from '../package.json';
    ```
2. Manually change the `externals` config to only include **native dependencies** (i.e. those that can't be built with webpack). E.g.:
    ```js
    externals: [],
    ```
**package.json**

1. Manually exclude any libraries built by `webpack` from `electron-builder` in `build.files`. If all of your dependencies are built by webpack, just add `"!**/node_modules/**/*"` as the last entry in the `build.files` array.

If your app uses multiple windows, you might also want to look into splitting your dependencies out into a separate build artifact in production (I believe the `dll` plugin is only used in dev mode).
