### ISSUE TITLE
[Feature request] option to turn off react-hot-loader and use simple remounting of root component

### ISSUE THREAD

**Issue by jedwards1211** [electron-react-boilerplate/electron-react-boilerplate#2150]
I've dealt with so many issues with react-hot-loader that I don't really trust it or think it's necessary.  In most of my projects I just add a `module.hot` hook to reload my `Root` component and remount it with `key={++reloads}`.  Would you be open to a PR for an environment variable to switch to this behavior?

**Comment by vikr01** [comment]
I don't think this is something of interest. `react-hot-loader` is widely used by developers using `react`. If you're having issues with it, I'd recommend filing bugs in their repo instead of just outright removing it.

Besides, doing something like `key={++reloads}` is really hacky.

**Comment by jedwards1211** [comment]
@vikr01 `key={++reloads}` is much simpler and more reliable than `react-hot-loader`.  `react-hot-loader` involves both a babel plugin and monkeypatching `React.createElement`, I'm not sure which sounds like more of a hack to you?

**Comment by vikr01** [comment]
@jedwards1211 Taunting people isn't a good way to get your point across.

> Do you even have any idea how `react-hot-loader` works under the hood?

I have some idea. I don't need to know all of it, that's one of the benefits of the module ecosystem.

You originally suggested that this *entire* project and *all* of its users should drop use of `react-hot-loader` because:
> I've dealt with so many issues

Now you're mentioning articles from >1 years ago to get your point across. You could've mentioned how it doesn't work with `react` hooks, which is something more recent.

You still haven't mentioned why there is even a need for a key on the root component, when keys are intended for components in an array. All you've said is that's it's better because it's not monkeypatching.

Your "solution" is completely remounting the *entire* root component, correct? Meaning that if even a small change occurred to the component, everything is remounted and states are reset?

**Comment by jedwards1211** [comment]
> I have some idea. I don't need to know all of it

Calling something simple like using a `key` to force a component to remount a hack is pretty brazen when you don't even acknowledge how `react-hot-loader` uses monkeypatching, which is considered by virtually all JS devs to be a hack, hence way more questionable in comparison to using a `key`.

Yes the key on the root component is to cause the entire root component to remount.  Keys are *primarily* intended for components in an array but they can also be used to indicate that React should completely replace an element instead of doing a virtual DOM diff deeper inside of it.

Yes it has the downside that states are reset.  However you're taking `react-hot-loader` for granted without giving due consideration/acknowledgment to the inherent risks in its complexity and ways it can waste much more developer time than states being reset.

I was only asking for an *option* to switch to remounting the entire root component after all.  This is what you get when you give a careless dismissive response that "doing something like `key={++reloads}` is really hacky" instead of actually *thinking* about how it compares to `react-hot-loader`'s complexity.

**Comment by jedwards1211** [comment]
> `react-hot-loader` is widely used by developers using `react`

This is a rhetorical fallacy called the bandwagon argument; it isn't really a concrete justification for using `react-hot-loader`.  Concrete justifications are: it's *convenient*.  It's *robust*.  It *saves time*.

**Comment by jedwards1211** [comment]
> Taunting people isn't a good way to get your point across.

Nor is dismissing their proposal without giving any thought to it?

**Comment by vikr01** [comment]
> Yes it has the downside that states are reset.

This would be removing a feature from the boilerplate, so again -- I don't think it's something of interest. We don't really have people complaining about it (I think you're the first).

> However you're taking `react-hot-loader` for granted without giving due consideration/acknowledgment to the inherent risks in its complexity and ways it can waste much more developer time than states being reset.

I'm aware it has its issues. It's a `devDependency`. It's not being shipped into production. Because it occasionally has issues and annoys people doesn't really seem like a good reason to completely remove it for *everyone*. Refreshing the page is still an option.

> Nor is dismissing their proposal without giving any thought to it?

If this was dismissed, the issue would be closed.

There are still other collaborators, members, contributors, and users who haven't spoken. I'm not making any decision, I'm just giving my input. Please refrain from making this something personal against me.

**Comment by jedwards1211** [comment]
@vikr01 seems like I still haven't made it clear that I was asking for an *option* to turn off `react-hot-loader` and use plain HMR instead.  I was never asking to remove `react-hot-loader` from this project.  Did my OP somehow make it seem like I was asking to remove it?

**Comment by vikr01** [comment]
@jedwards1211 Ah I see. Yeah that's doable. If you'd like to make a PR for that, feel free.

**Comment by jedwards1211** [comment]
Okay.  I can make where setting an environment variable like `PLAIN_HMR=1` will turn on this behavior
