### ISSUE TITLE
start-main-dev does not use webpack

### ISSUE THREAD

**Issue by Kilian** [electron-react-boilerplate/electron-react-boilerplate#2151]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)

## Expected Behavior
When running `yarn run dev` I expect the  webpack base config to be applied, so that e.g. the webpack.DefinePlugin has its settings applied. 
 

## Current Behavior

The current `start-main-dev` does not seem to use webpack but uses @babel/register directly, meaning that any values specified in the webpack base config are not used: https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/next/package.json#L30

## Possible Solution

Run webpack for the main renderer when developing too.

## Steps to Reproduce (for bugs)

1. Define a value using webpack.DefinePlugin in `webpack.config.base.js`
2. console.log/use it in `main.dev.js`
3. run `yarn run dev`, 
4. get an ReferenceError for an undefined variable
5. run `yarn build`
6. See the build succeed

## Context

I have a native module that I want to conditionally import only on a specific platform, as it will fail on other platforms. Since all `require()`s get resolved, i need to do the require itself conditionally. To do this I use a DefinePlugin to set the value I'm `require()`ing, with a different require depending on platform.

## Your Environment

- Node version : 10
- Version or Branch used : master
- Operating System and version : linux 18.04

**Comment by eric-burel** [comment]
Hi,

In addition, I would suggest to have the same output filename for prod and dev, `main.js`. This way, we can correctly set the `package.json` `main` prop (`"main" : "./app/main.js"`), and run Electron on the package.json instead of the app itself.

Se tthis SO question: https://stackoverflow.com/questions/35630934/app-getpathuserdata-seems-to-give-the-wrong-path/54904109#54904109

By running `electron folder/to/packagejson` instead of `electron foder/to/main.dev.js` guarantees that you get the same app name in development and prod. This is especially useful for `userData` path computation.
