### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by namgk** [electron-react-boilerplate/electron-react-boilerplate#2195]
How do we follow security advices from here: https://electronjs.org/docs/tutorial/security

In particular, how do we remove access to node/process API from app.html? And also enabling the use of preload script (probably via webpack and babel as well)?

Thanks

PS/ 
Might be related to https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/1309#issuecomment-343876650, but

> a boilerplate which isn't totally focused on security

-> really? 

Has security concerns ever crossed your plan?

**Comment by lvkins** [comment]
Well, thats the things about JS developers, they just eat them libraries and don't really care about the security or how good is the library written. It's like _let's just trust the library maintainer and live in a good hope_ because _this library solves my problem and I don't care how_. This boilerplate snugs you with 1GB of dependencies, that is, for a simple click counter which is just insane.

If I could recommend you anything, take a peek at the [fiddle](https://github.com/electron/fiddle) library from electron and see how they implement React 👍

**Comment by amilajack** [comment]
That fiddle actually has the same security limitations the boilerplate does:
https://github.com/electron/fiddle/blob/fdf03dff9b097102dbdc4dd0698a9010ef82ceb7/src/main/windows.ts#L24

**Comment by amilajack** [comment]
> Has security concerns ever crossed your plan?

@namgk it certainly has but we're short on resources in terms on maintenance. Some donations would be appreciated so we can get the ball moving on this

**Comment by reZach** [comment]
@namgk it takes a lot of work to support security. Especially in Electron, supporting packages must be written in a secure way in order for them to work. I have a secure template that I maintain that you may use if you are concerned with security: [`secure-electron-template`](https://github.com/reZach/secure-electron-template).
