### ISSUE TITLE
Wrong user data app folder name in dev mode

### ISSUE THREAD

**Issue by kevincastejon** [electron-react-boilerplate/electron-react-boilerplate#2197]
The dev mode application folder has a wrong name ('Electron' instead of the app name), so app.getPath('userData') leads to "[...]/Roaming/Electron" instead of "[...]/Roaming/ElectronReact".
The production mode has the right expected behaviour.

## Expected Behavior

Typing yarn dev create an application folder into the OS 'userData' location which name is the same as the application (as in production mode behaviour).

## Current Behavior

Typing yarn dev will create an application folder into the OS 'userData' location, with a wrong name (Electron instead of the app name).

## Possible Solution

Partial solution : https://stackoverflow.com/questions/35630934/app-getpathuserdata-seems-to-give-the-wrong-path
Add the following package.json file into the 'app' directory :
{
  "name": "electron-react-boilerplate",
  "main": "./main.dev.js"
}
This will generate the application folder with the app name, but an 'Electron' folder is generated as well (itself containing a 'logs' folder)

## Steps to Reproduce (for bugs)

1.
clone the repo
2.
install dependencies (yarn)
3.
launch dev mode (yarn dev)
4.
log Electron.app.getPath('userData') (returns DRIVE_LETTER:\Users\USERNAME\AppData\Roaming\Electron for windows)

## Context

Storing data into an application folder named 'Electron' could cause conflicts when multiple projects are using the same boilerplate, and so the same folder into 'AppData/Roaming'

## Your Environment

- Node version : 10.15.1
- Version or Branch used : master
- Operating System and version : windows 10

**Comment by clementAC** [comment]
This issue cannot be closed and need further investigation on how to solve it. 
As @kevincastejon  said the userData folder is always named Electron on dev environment and it cause conflict when creating several project with ERB. 

I'm not a specialist but what cause the first generation of the pakcage.json to be false?

In a logical point of view it's a bit absurd to regenerate on the flight the package.json without correcting the root cause of the malformation.
