### ISSUE TITLE
React Hooks not working correctly

### ISSUE THREAD

**Issue by ivanjeremic** [electron-react-boilerplate/electron-react-boilerplate#2265]
I have a really wired problem and console is not giving any errors, {setState} hook is not working in my functional components, I add the counter to increment on button click for testing and the increment is not working but what is interesting it can read the state, also the components that have {useState} stop rendering any component when hitting same route again it says 
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
 but it is clearly everything correct , Why every component is disappearing from the screen when hitting same route again?

**Comment by ivanjeremic** [comment]
I have upgraded React and i'm still not able to get `{useState}` working in functional components. Any idea why?

**Comment by conroywhitney** [comment]
Hey @ivanjeremic --

I had this issue, too. Super annoying, and it's affecting tonnes of repos around the web. But good news is, there's a fix (kinda):

PR #2220 upgrades `react-hot-loader` to the latest (right now, that's `^4.12.11`)

You'll see in that PR that there's a few changes (like using `hot(Root)` and using `@hot-loader/react-dom` instead of `react-dom`)

However, as pointed Issue #2266, we're all still getting this error:

```
React-Hot-Loader: misconfiguration detected, using production version in non-production environment.

React-Hot-Loader: Hot Module Replacement is not enabled.

React-Hot-Loader: react-🔥-dom patch is not detected. React 16.6+ features may not work.
```

So follow Issue #2266 to see the fix for that whenever it comes. I couldn't figure it out myself.

If you're curious as to why this was happening, it looks like the older version of `react-hot-loader` converts functional components into class components behind the scenes, and hooks don't work in class components:

https://github.com/gaearon/react-hot-loader/issues/1088#issuecomment-433537974

Another option is just to not use functional components, but stick with classes if you wanna use state. After hours of messing with this error (and it still not being fixed), I'm still not sure if it was worth it. 🤪

**Comment by blakelmason** [comment]
Heyo, I tried updating react-hot-loader to the newest version and got it working if you're still having an issue with this.

**Comment by blakelmason** [comment]
Oh, I forgot to mention I also upgraded react and react-dom to the latest versions as well.

**Comment by ivanjeremic** [comment]
Thanks, Do you know if this package is still well maintained? I hope there will be a version without so much dependencies like hot-loader, Redux, Flow .. it is really to much I think.

**Comment by blakelmason** [comment]
I don't know if it is still well maintained. I asked myself that same question because I'm trying to find a good boilerplate to use react with electron. This one is the best I have found so far, but yea all of the dependencies are a bit overwhelming. I'm trying to peel off some of them manually, and so far have found some success. I got stuck on the react hooks part, found your question had not been solved, and just fixed it myself today. I have also successfully removed to redux portion of it too, and I think I might have a good base to finally work from.

**Comment by ivanjeremic** [comment]
Hooks work now on my side, but this Boilerplate is still full of Class Components, the React team clearly said 2018 hooks are the future and still so many class components around here. Also the Context-api + useReducer is more then enough for Electron Apps, If I would have time I would maintain a Boilerplate myself but no time to do it alone.

**Comment by 1111mp** [comment]
@catalinmiron I have this problem, too.But none of the fixes worked.Have you finally solved the problem？

**Comment by 1111mp** [comment]
I found a solution here: [https://github.com/gaearon/react-hot-loader/issues/1333](url)

**Comment by lucca180** [comment]
Not working for me too and none of the solutions above worked. I'm using the latest version (0.18.1). Tried a clean clone and the error persist.

**Comment by rahulpsd18** [comment]
I have a weird problem. 

Everything works fine in development mode but as soon as I start it in production mode I get error with https://reactjs.org/docs/error-decoder.html/?invariant=321
