### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by fandy** [electron-react-boilerplate/electron-react-boilerplate#2342]
In the [docs](https://electron-react-boilerplate.js.org/docs/faq/#why-not-typescript), it seems like TS is now on the roadmap. Is there any place to track the ETA for this?

**Comment by amilajack** [comment]
Unfortunately I'm the only active contributor to this project so it might take some time to implement, test, and cut a release. Feel free to [fund the project](https://opencollective.com/electron-react-boilerplate-594).

**Comment by AhmedKorim** [comment]
Hey I've done some progress on development side, but i had to change the structure 
I works fine on the development side but packing failed due to index.js not found
the current file structure

├── CHANGELOG.md
├── CODE_OF_CONDUCT.md
├── LICENSE
├── README.md
├── appveyor.yml
├── babel.config.js
├── build
│   ├── dist
│   │   ├── 088a34f78f530102fd9661173b4a4f26.eot
│   │   ├── 273dc9bf9778fd37fa61357645d46a28.ttf
│   │   ├── 2aa6edf8f296a43b32df35f330b7c81c.ttf
│   │   ├── 3ac49cb33f43a6471f21ab3df40d1b1e.eot
│   │   ├── 7a5de9b08012e4da40504f2cf126a351.svg
│   │   ├── 7fb1cdd9c3b889161216a13267b55fe2.eot
│   │   ├── 822d94f19fe57477865209e1242a3c63.woff2
│   │   ├── 93f284548b42ab76fe3fd03a9d3a2180.woff
│   │   ├── 9efb86976bd53e159166c12365f61e25.woff2
│   │   ├── a57bcf76c178aee452db7a57b75509b6.woff
│   │   ├── d2e53334c22a9a4937bc26e84b36e1e0.svg
│   │   ├── d72293118cda50ec50c39957d9d836d0.svg
│   │   ├── ece54318791c51b52dfdc689efdb6271.ttf
│   │   ├── f4920c94c0861c537f72ba36590f6362.woff
│   │   ├── f6121be597a72928f54e7ab5b95512a1.woff2
│   │   ├── renderer.prod.js
│   │   ├── renderer.prod.js.LICENSE
│   │   ├── renderer.prod.js.map
│   │   ├── style.css
│   │   └── style.css.map
│   ├── main.prod.js
│   ├── main.prod.js.LICENSE
│   └── main.prod.js.map
├── configs
│   ├── webpack.config.base.js
│   ├── webpack.config.eslint.js
│   ├── webpack.config.main.prod.babel.js
│   ├── webpack.config.renderer.dev.babel.js
│   ├── webpack.config.renderer.dev.dll.babel.js
│   └── webpack.config.renderer.prod.babel.js
├── dll
│   ├── renderer.dev.dll.js
│   └── renderer.json
├── flow-typed
│   ├── module_vx.x.x.js
│   └── npm
│       ├── @babel
│       │   ├── core_vx.x.x.js
│       │   ├── plugin-proposal-class-properties_vx.x.x.js
│       │   ├── plugin-proposal-decorators_vx.x.x.js
│       │   ├── plugin-proposal-do-expressions_vx.x.x.js
│       │   ├── plugin-proposal-export-default-from_vx.x.x.js
│       │   ├── plugin-proposal-export-namespace-from_vx.x.x.js
│       │   ├── plugin-proposal-function-bind_vx.x.x.js
│       │   ├── plugin-proposal-function-sent_vx.x.x.js
│       │   ├── plugin-proposal-json-strings_vx.x.x.js
│       │   ├── plugin-proposal-logical-assignment-operators_vx.x.x.js
│       │   ├── plugin-proposal-nullish-coalescing-operator_vx.x.x.js
│       │   ├── plugin-proposal-numeric-separator_vx.x.x.js
│       │   ├── plugin-proposal-optional-chaining_vx.x.x.js
│       │   ├── plugin-proposal-pipeline-operator_vx.x.x.js
│       │   ├── plugin-proposal-throw-expressions_vx.x.x.js
│       │   ├── plugin-syntax-dynamic-import_vx.x.x.js
│       │   ├── plugin-syntax-import-meta_vx.x.x.js
│       │   ├── plugin-transform-react-constant-elements_vx.x.x.js
│       │   ├── plugin-transform-react-inline-elements_vx.x.x.js
│       │   ├── preset-env_vx.x.x.js
│       │   ├── preset-flow_vx.x.x.js
│       │   ├── preset-react_vx.x.x.js
│       │   ├── preset-typescript_vx.x.x.js
│       │   └── register_v7.x.x.js
│       ├── @fortawesome
│       │   └── fontawesome-free_vx.x.x.js
│       ├── @hot-loader
│       │   └── react-dom_vx.x.x.js
│       ├── @material-ui
│       │   └── core_vx.x.x.js
│       ├── @types
│       │   └── electron_vx.x.x.js
│       ├── babel-core_vx.x.x.js
│       ├── babel-eslint_vx.x.x.js
│       ├── babel-jest_vx.x.x.js
│       ├── babel-loader_vx.x.x.js
│       ├── babel-plugin-const-enum_vx.x.x.js
│       ├── babel-plugin-dev-expression_vx.x.x.js
│       ├── babel-plugin-transform-react-remove-prop-types_vx.x.x.js
│       ├── chalk_vx.x.x.js
│       ├── concurrently_vx.x.x.js
│       ├── connected-react-router_vx.x.x.js
│       ├── core-js_vx.x.x.js
│       ├── cross-env_vx.x.x.js
│       ├── cross-spawn_vx.x.x.js
│       ├── css-loader_vx.x.x.js
│       ├── detect-port_vx.x.x.js
│       ├── devtron_vx.x.x.js
│       ├── electron-builder_vx.x.x.js
│       ├── electron-debug_vx.x.x.js
│       ├── electron-devtools-installer_vx.x.x.js
│       ├── electron-log_vx.x.x.js
│       ├── electron-rebuild_vx.x.x.js
│       ├── electron-updater_vx.x.x.js
│       ├── electron_vx.x.x.js
│       ├── enzyme-adapter-react-16_vx.x.x.js
│       ├── enzyme-to-json_vx.x.x.js
│       ├── enzyme_v3.x.x.js
│       ├── eslint-config-airbnb_vx.x.x.js
│       ├── eslint-config-erb_vx.x.x.js
│       ├── eslint-config-prettier_vx.x.x.js
│       ├── eslint-formatter-pretty_vx.x.x.js
│       ├── eslint-import-resolver-webpack_vx.x.x.js
│       ├── eslint-plugin-compat_vx.x.x.js
│       ├── eslint-plugin-flowtype_vx.x.x.js
│       ├── eslint-plugin-import_vx.x.x.js
│       ├── eslint-plugin-jest_vx.x.x.js
│       ├── eslint-plugin-jsx-a11y_vx.x.x.js
│       ├── eslint-plugin-prettier_vx.x.x.js
│       ├── eslint-plugin-promise_vx.x.x.js
│       ├── eslint-plugin-react_vx.x.x.js
│       ├── eslint-plugin-testcafe_vx.x.x.js
│       ├── eslint_vx.x.x.js
│       ├── fbjs-scripts_vx.x.x.js
│       ├── file-loader_vx.x.x.js
│       ├── flow-bin_v0.x.x.js
│       ├── flow-runtime_vx.x.x.js
│       ├── flow-typed_vx.x.x.js
│       ├── fork-ts-checker-webpack-plugin_vx.x.x.js
│       ├── history_v4.10.x.js
│       ├── husky_vx.x.x.js
│       ├── identity-obj-proxy_vx.x.x.js
│       ├── jest_v24.x.x.js
│       ├── lint-staged_vx.x.x.js
│       ├── mini-css-extract-plugin_vx.x.x.js
│       ├── node-sass_vx.x.x.js
│       ├── opencollective-postinstall_vx.x.x.js
│       ├── optimize-css-assets-webpack-plugin_vx.x.x.js
│       ├── prettier_v1.x.x.js
│       ├── react-animation-group_vx.x.x.js
│       ├── react-hot-loader_v4.6.x.js
│       ├── react-redux_v7.x.x.js
│       ├── react-router-dom_v5.x.x.js
│       ├── react-router_v5.x.x.js
│       ├── react-spring_vx.x.x.js
│       ├── react-test-renderer_v16.x.x.js
│       ├── redux-logger_vx.x.x.js
│       ├── redux-thunk_vx.x.x.js
│       ├── redux_v4.x.x.js
│       ├── rimraf_vx.x.x.js
│       ├── sass-loader_vx.x.x.js
│       ├── sinon_v7.x.x.js
│       ├── source-map-support_vx.x.x.js
│       ├── spectron_vx.x.x.js
│       ├── style-loader_vx.x.x.js
│       ├── styled-components_v4.x.x.js
│       ├── stylelint-config-prettier_vx.x.x.js
│       ├── stylelint-config-standard_vx.x.x.js
│       ├── stylelint_vx.x.x.js
│       ├── terser-webpack-plugin_vx.x.x.js
│       ├── testcafe-browser-provider-electron_vx.x.x.js
│       ├── testcafe-react-selectors_vx.x.x.js
│       ├── testcafe_vx.x.x.js
│       ├── url-loader_vx.x.x.js
│       ├── webpack-bundle-analyzer_vx.x.x.js
│       ├── webpack-cli_vx.x.x.js
│       ├── webpack-dev-server_vx.x.x.js
│       ├── webpack-merge_vx.x.x.js
│       ├── webpack_v4.x.x.js
│       └── yarn_vx.x.x.js
├── internals
│   ├── flow
│   │   ├── CSSModule.js.flow
│   │   └── WebpackAsset.js.flow
│   ├── img
│   │   ├── erb-banner.png
│   │   ├── erb-logo.png
│   │   ├── eslint-padded-90.png
│   │   ├── eslint-padded.png
│   │   ├── eslint.png
│   │   ├── flow-padded-90.png
│   │   ├── flow-padded.png
│   │   ├── flow.png
│   │   ├── jest-padded-90.png
│   │   ├── jest-padded.png
│   │   ├── jest.png
│   │   ├── js-padded.png
│   │   ├── js.png
│   │   ├── npm.png
│   │   ├── react-padded-90.png
│   │   ├── react-padded.png
│   │   ├── react-router-padded-90.png
│   │   ├── react-router-padded.png
│   │   ├── react-router.png
│   │   ├── react.png
│   │   ├── redux-padded-90.png
│   │   ├── redux-padded.png
│   │   ├── redux.png
│   │   ├── webpack-padded-90.png
│   │   ├── webpack-padded.png
│   │   ├── webpack.png
│   │   ├── yarn-padded-90.png
│   │   ├── yarn-padded.png
│   │   └── yarn.png
│   ├── mocks
│   │   └── fileMock.js
│   └── scripts
│       ├── BabelRegister.js
│       ├── CheckBuildsExist.js
│       ├── CheckNativeDep.js
│       ├── CheckNodeEnv.js
│       ├── CheckPortInUse.js
│       ├── CheckYarn.js
│       └── ElectronRebuild.js
├── package.json
├── renovate.json
├── resources
│   ├── icon.icns
│   ├── icon.ico
│   ├── icon.png
│   └── icons
│       ├── 1024x1024.png
│       ├── 128x128.png
│       ├── 16x16.png
│       ├── 24x24.png
│       ├── 256x256.png
│       ├── 32x32.png
│       ├── 48x48.png
│       ├── 512x512.png
│       ├── 64x64.png
│       └── 96x96.png
├── src
│   ├── app
│   │   ├── Routes.js
│   │   ├── actions
│   │   │   └── counter.js
│   │   ├── app.global.css
│   │   ├── app.html
│   │   ├── app.icns
│   │   ├── components
│   │   │   ├── Home.css
│   │   │   ├── Home.tsx
│   │   │   └── test.tsx
│   │   ├── constants
│   │   │   └── routes.json
│   │   ├── containers
│   │   │   ├── App.js
│   │   │   ├── CounterPage.js
│   │   │   ├── HomePage.js
│   │   │   └── Root.js
│   │   ├── index.js
│   │   ├── main.dev.ts
│   │   ├── main.prod.js.LICENSE
│   │   ├── menu.js
│   │   ├── package.json
│   │   ├── reducers
│   │   │   ├── counter.js
│   │   │   ├── index.js
│   │   │   └── types.js
│   │   ├── store
│   │   │   ├── configureStore.dev.js
│   │   │   ├── configureStore.js
│   │   │   └── configureStore.prod.js
│   │   ├── utils
│   │   └── yarn.lock
│   ├── assets
│   ├── generated
│   ├── test
│   │   ├── actions
│   │   │   ├── __snapshots__
│   │   │   │   └── counter.spec.js.snap
│   │   │   └── counter.spec.js
│   │   ├── components
│   │   │   ├── Counter.spec.js
│   │   │   └── __snapshots__
│   │   │       └── Counter.spec.js.snap
│   │   ├── containers
│   │   │   └── CounterPage.spec.js
│   │   ├── e2e
│   │   │   ├── HomePage.e2e.js
│   │   │   └── helpers.js
│   │   ├── example.js
│   │   └── reducers
│   │       ├── __snapshots__
│   │       │   └── counter.spec.js.snap
│   │       └── counter.spec.js
│   └── utils
│       └── test.ts
├── tsconfig.json
└── yarn.lock

I'm still working on it, 'd be great if  You can give me a hint about how to make it package from the build folder only

**Comment by amilajack** [comment]
Fixed in https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2363
