### ISSUE TITLE
how to use ipcRender in the project

### ISSUE THREAD

**Issue by cornwang** [electron-react-boilerplate/electron-react-boilerplate#2414]
hello, now i have some question
1. if i want to use ipcRender in my Componet ,like this
![image](https://user-images.githubusercontent.com/27324050/76812783-f2d53780-6830-11ea-959f-eeca22cd660b.png)
but when the run 
![image](https://user-images.githubusercontent.com/27324050/76812811-0da7ac00-6831-11ea-9a1a-ae89c3751f5e.png)
so how to use ipcRender?
2. who can tell me  why it's run,the router is '/'?

**Comment by dbvrac** [comment]
It would help to have a better idea of what you are trying to accomplish. I see you are using `ipcRender`, but do you have an `ipcMain` somewhere? I'm pretty new to this, and the Electron docs and various help forums may be of more help to you since your situation is not ERB specific.
That said, I have functionality in my two-window ERB application to allow an event in one window to trigger an event in the other. I found this article very helpful. https://ourcodeworld.com/articles/read/536/how-to-send-information-from-one-window-to-another-in-electron-framework

**Comment by cornwang** [comment]
@dbvrac  Thank you, this error disappeared when I restarted the project
