### ISSUE TITLE
when i  npm run package ,it's error

### ISSUE THREAD

**Issue by cornwang** [electron-react-boilerplate/electron-react-boilerplate#2415]
![image](https://user-images.githubusercontent.com/27324050/76944542-2a7cd600-693c-11ea-86ee-ed4be17e36a8.png)

and  when i npm run start, the electronApp will white screen

![image](https://user-images.githubusercontent.com/27324050/76944787-92cbb780-693c-11ea-9e3a-22e87b9c8894.png)

but when i npm run dev  it's ok
what happen?

**Comment by WilsonCazarre** [comment]
First I recommend you to use `yarn start` instead of `npm run start`.
Either way, you probably add some wrong field to your package.json.

As you can see, Electron Builder is using the configuration specified in `package.json`, more specific in the `build` field. If you can post your `package.json` here it would be great.
That's why you don't find this problem in `npm run dev`. This configuration does not "build" the app before launch.

**Comment by cornwang** [comment]
code error
