### ISSUE TITLE
Another "ERROR in dll renderer" issue

### ISSUE THREAD

**Issue by amilich** [electron-react-boilerplate/electron-react-boilerplate#2438]
I see the issue "ERROR in dll renderer" when installing a package via yarn; solutions in past issues aren't complete or don't work for me.

## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Steps to Reproduce (for bugs)

1. From readme: `git clone --depth 1 --single-branch https://github.com/electron-react-boilerplate/electron-react-boilerplate.git your-project-name` then `cd your-project-name` then `yarn`

2. `yarn add secure-remote-password`

Error appears - 
```
ERROR in dll renderer
Module not found: Error: Can't resolve 'secure-remote-password' in '---path---/your-project-name'
 @ dll renderer renderer[21]
```

## Context

Just trying to install the module `secure-remote-password` :)
Removing `node_modules` does not work (issue [here](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/1752))

## Your Environment

- Node version : 13.11.0
- Version or Branch used : master 
- Operating System and version : Catalina 10.15.2
- Link to your project :

**Comment by steveetm** [comment]
This is due how `secure-remote-password` created as a node module and how the renderer build tries to assemble the bundle.
The problem is, that webpack is right here, you can't really resolve `secure-remote-password`, because there is no such thing. Just try to require it in plain node repl. Even the docs suggests you should require either `secure-remote-password/server` or `/client`. This makes sense as package.json of that package contains no main field, so you can't know what to resolve when someone request the package itself.

If you go to `webbpack.config.renderer.dev.dll.babel.js` find `entry` and try this:
```
  entry: {
    renderer: [
      ...Object.keys(dependencies || {}),
      'secure-remote-password/client'
    ].filter(key => key !== 'secure-remote-password')
  },
```
As by default we try to put every package from the root `package.json` into the renderer's dll bundle. But that is impossible for packages without main field, so we filter out this one, and add a resolvable module.

Please not this is an ugly workaround, not sure how to solve this properly.
We should either preparse `dependency` key of package.json and filter out mainless packages and show a proper warning or have an other key where you could override such packages how to import them by webpack bundler.

**Comment by amilich** [comment]
This worked - thanks for replyin! Will update if I end up making any of the other changes to fix this dependency issue.

**Comment by luojinzhang** [comment]
this is still happening with boilerplate 4.6.0. Using node 16.15.0. It was working fine, then I used nvm to switch to another version and then when i switched back, this happened. The workaround helped but I don't think it should be marked as solved. Thanks.
