### ISSUE TITLE
React Router v6

### ISSUE THREAD

**Issue by jooohhn** [electron-react-boilerplate/electron-react-boilerplate#2460]
It'd be a good enhancement to update to react-router@v6 once it's out of alpha. Features smaller bundle size and better routing features. I can take a look at migrating API changes once they release 😃

Reference: https://reacttraining.com/blog/react-router-v6-pre/

**Comment by ivanjeremic** [comment]
Yes, It is a major improvement I listened to the maintainer on a podcast talking about the new react-router, we need this asap, I will try to implement this today and see how it goes.

**Comment by ivanjeremic** [comment]
I made a branch in my fork to test it out, it navigates correctly but with an error, the navigated page appears again only on force refresh, maybe anyone here or @amilajack  can take a look. 
**Changes I made:** _adding react-router-dom v6 + replacing Switch with Routes in Router.tsx + Renaming Routes.tsx to Router.tsx because of conflict with import of v6_
https://github.com/ivanjeremic/electron-react-boilerplate/tree/react-router-v6

**Comment by jooohhn** [comment]
@ivanjeremic is there an error code in the console?

**Comment by ivanjeremic** [comment]
> @ivanjeremic is there an error code in the console?

I'm not on the PC right now but yes it was a console error in the browser, I was not able to fix in the short time I had, but you can download my fork and maybe take a look.

**Comment by ivanjeremic** [comment]
@amilajack  Normally I would never suggest using a beta library but in this case, I hope that this boilerplate switches tomorrow to v6 it is safe to use and much less buggy, I don't need to remind anyone how many people opened issues here because routes break or something in the order messed things up then we need `exact` and and and... with v6 this is solved.
