### ISSUE TITLE
Use jsx instead of ts

### ISSUE THREAD

**Issue by amir04lm26** [electron-react-boilerplate/electron-react-boilerplate#2475]
Thanks for your great boilerplate, I'm wondering to ask how can I change every ts file config for jsx config(e.x. Webpack).
sincerely yours.

**Comment by cksachdev** [comment]
I was trying to figure out the js version of ERB and below are my findings:
- ERB 0.18.0 was the last version which doesn't have any .ts files
- ERB 0.18.1 changed couple of components to typescript
- These versions can be downloaded from the Tags/Release

I noticed in package.json there are commands which indicate hot reloading is possible for both electron main process and renderer process.
```
"dev": "cross-env START_HOT=1 node -r @babel/register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev",
"start-main-dev": "cross-env HOT=1 NODE_ENV=development electron -r @babel/register ./app/main.dev.js",
"start-renderer-dev": "cross-env NODE_ENV=development webpack-dev-server --config configs/webpack.config.renderer.dev.babel.js"
```
Question. Hot-reloading seems to work only for the renderer process, if I make any changes in main process, app doesn't refresh or relaunch. Any idea how to make it work?

**Comment by amilajack** [comment]
Thanks for the neatly outlined questions.

> Question 1. Hot-reloading seems to work only for the renderer process, if I make any changes in main process, app doesn't refresh or relaunch. Any idea how to make it work?

Reloading main process is much more difficult than hot reloading renderer process since electron api design is very stateful. There have been attempts to implement this in the past but none worked well enough

> Question 2. Is it possible to configure to launch the electron app on second monitor, such that I don't have to manually move it?

Yes you can. Ask electron community for more details on this.

> Question 3. Using 0.18.0 as the boilerplate, is there any latest version or branch I should refer to, to work only on the javascript version of ERB?

A common request in ERB version <= 0.18.0 was to add TS support. Now that we've added it we're getting requests about having a JS version. Maintaining two versions is quite difficult so I'm still thinking how we should proceed here.

Since the boilerplate optimizes for large scale electron apps, it makes sense for it to default to TS instead of JS. Also migrating from JS to TS is harder than TS to JS.

**Comment by amilajack** [comment]
Resolving this in #2476

**Comment by cksachdev** [comment]
@amilajack Thanks for sharing the details. I have looked around other boilerplate codes and found https://github.com/jschr/electron-react-redux-boilerplate where hotreloading works properly for main process as well. 
Above repo uses gulp with watcher for hotreloading, working example app https://github.com/mullvad/mullvadvpn-app/tree/9b2324c71d4419b1a0be322d540146b2e0dcbe13/gui/tasks

Hope you find this useful. Looking forward to #2476 such that I can start with this boilerplate.
