### ISSUE TITLE
System tray icon

### ISSUE THREAD

**Issue by dugiwarc** [electron-react-boilerplate/electron-react-boilerplate#2511]
System tray icon shows in development mode, but not after packaging the app.
Any workaround to this?

This is how I add the icon 
```
let tray = new Tray(
      nativeImage.createFromPath(
        path.join(__dirname, 'resources', 'icons', '24x24.png')
      )
    );
```

**Comment by masonlee** [comment]
I'm having the same issue.  What do we need to do to get our main process image assets into the packaged app?

**Comment by masonlee** [comment]
I figured it out with help from the [electron-builder docs](https://www.electron.build/configuration/contents#extraresources) and https://stackoverflow.com/a/46033483/530309

I moved my tray icon into a new folder called `[my_project]/extraResources`.

Then I added a definition for "extraResources" in `[my_project]/package.json`.  For me, that looks like:

```
  "build": {
    "extraResources": [
      "./extraResources/**"
    ],
   ...
```

Then, when referencing the tray icon by name, I use a new getAssetPath() function so that it can be found in dev mode and when packaged.  Here's that:

```
import path from 'path';

const EXTRA_RESOURCES_PATH = app.isPackaged
  ? path.join(process.resourcesPath, 'extraResources')
  : path.join(__dirname, '../../extraResources');  // Your relative path may be different!

const getAssetPath = (resourceFilename: string): string => {
  return path.join(EXTRA_RESOURCES_PATH, resourceFilename);
};
```

Hope this helps others who are new to Electron.

**Comment by paragbaxi** [comment]
Does anyone have a repo example that uses erb with a working tray from "yarn package"?

**Comment by patrickkreuzenort** [comment]
My problem with packaging of an embedded sqlite db with prepared data is now solved, thank you very much!
