### ISSUE TITLE
Exposing functions to renderers using contextbridge

### ISSUE THREAD

**Issue by TheRogue76** [electron-react-boilerplate/electron-react-boilerplate#2625]
## Summary

Hi. 
I've just started using electron-react-boilerplate and i have been wondering how to expose APIs to my renderers without preload. i know ERB creates it's own production preload using the webpack.config files but i don't know how to add anything to them. Any help would be appreciated.
Thanks

**Comment by amilajack** [comment]
ERB doesn't target preload as the default anymore. I'm also not sure if I understand what you're asking. Can you clarify the question.

**Comment by ahmetuysal** [comment]
@amilajack can you explain how ERB does not target preload as default? I have limited webpack experience and I also wanted to expose functions to react side using context bridge and subscribe to this functions in useEffect hooks, however, since ERB also uses preload, these references are undefined. (I can see these functions on developer tools console, but they are undefined inside react useEffect hooks) 
How can I accomplish such a thing? I tried to remove `webPreferences.preload` from browser window options but electron opens with an empty screen without my react application in this case.

Thanks

**Comment by kyranjamie** [comment]
This is a legitimate concern. Erb's method of passing the entire script to `preload` in production isn't Electron's intended use of it.

> preload: - Specifies a script that will be loaded before other scripts run in the page. This script will always have access to node APIs no matter whether node integration is turned on or off. The value should be the absolute file path to the script. When node integration is turned off, the preload script can reintroduce Node global symbols back to the global scope. See example here.

It's a really bad default setting as it poses real security risks.

**Comment by jimji1005** [comment]
Agreeing with the above, latest version has this for prod 
`preload: path.join(__dirname, 'dist/renderer.prod.js'),`
which is created by
```
output: {
    path: path.join(__dirname, '..', 'app/dist'),
    publicPath: './dist/',
    filename: 'renderer.prod.js',
  },```

Basically dumping entire dist folder in there. which present another issue, you can't really add a prod only preload if we use the default setup.
