### ISSUE TITLE
Why is BrowserRouter being used not HashRouter?

### ISSUE THREAD

**Issue by RishabhVerma** [electron-react-boilerplate/electron-react-boilerplate#2684]
HashRouter supports better support when the react app is not served through a server. I couldn't make many changes like opening the app on a specific route through `loadUrl` method of electron etc. 

I have switched to a BrowserRouter for my implementation? Is there any reason to move to BrowserRouter?

**Comment by amilajack** [comment]
Historically there have been some issues with BrowserRouter in the electron context. I can reinvestigate to see if these issues still persist

**Comment by Sensiblemnd** [comment]
Actually Rout is broken in currect build.

**Comment by JuneKimDev** [comment]
Electron-forge recommends to use `MemoryRouter` instead of `BrowserRouter` for "[Browser history will work in development but not in production as your code will be loaded from the filesystem not a webserver.](https://www.electronforge.io/config/plugins/webpack#how-do-i-do-virtual-routing)"

Maybe ERB should do the same.
