### ISSUE TITLE
yarn package does not support --mac --arm64 arguments ?

### ISSUE THREAD

**Issue by ammarrush** [electron-react-boilerplate/electron-react-boilerplate#2777]
I am using macOS Big Sur 11.1 and chip Apple M1 when I run `yarn package` the package is built for darwin arch=x64 so I thought automatically creating package for arm64 does not exist so I tried `yarn package --mac --arm64` but the package is still built for darwin x64.

Is there a way to build the package for arm64 ? I see that electron-builder now supports arm64 argument for building.

**Comment by star-scraper** [comment]
I just opened a PR yesterday that got merged today so that you don't have to pass any additional params.  The version of Electron Builder should be updated once you remove and re-install your node modules.  Try pulling the latest change from the repo or just update your version of electron-builder to the current latest.  I was able to get 'yarn package' to run fine now with an arm64 / darwin build by default without having to pass anymore params.

**Comment by ammarrush** [comment]
> I just opened a PR yesterday that got merged today so that you don't have to pass any additional params. The version of Electron Builder should be updated once you remove and re-install your node modules. Try pulling the latest change from the repo or just update your version of electron-builder to the current latest. I was able to get 'yarn package' to run fine now with an arm64 / darwin build by default without having to pass anymore params.

I did what you said, it still doesn’t work without passing additional params. I change my package command to be like this
`rm -rf src/dist && yarn build && electron-builder --mac --arm64 --publish never` and then it worked.
