### ISSUE TITLE
add docs for using js instead of ts

### ISSUE THREAD

**Issue by zedtux** [electron-react-boilerplate/electron-react-boilerplate#2778]
## Summary

What are the steps to allow using js and jsx instead of ts and tsx?
Do you have a wiki page or documentation on how to do that please? 🙏

**Comment by balsigergil** [comment]
It is not very complicated :
- Rename all `.ts` to `.js` (except files in the configs folder), all `.tsx` in `.jsx`
- Update files content accordingly (remove interfaces, type declarations, etc...) 
- Update the scripts in `package.json` and entry points in webpack configs

I did all of this [here](https://github.com/balsigergil/electron-react-boilerplate) so the boilerplate works without TypeScript.
However I encourage you to learn TypeScript. It's very simple and soooo useful, really.

**Comment by zedtux** [comment]
Thank you @balsigergil for your comment but  I think you are missing all the Eslint stuff... At least I remember having a bit of hard time to remove all the typescript things in order to get the whole project working properly.

I've open this issue, not because I'm not able to do it, but more to get the official right way to do it.

> However I encourage you to learn TypeScript. It's very simple and soooo useful, really.

It's not really about TS being useful and learning it, it's that for quick and small projects it doesn't really make sense, at least to me.

**Comment by balsigergil** [comment]
Yes I did not actually think about ESLint.
Personally I don't think there is an official way to use JS instead of TS but this is what I found for ESLint: 
There is a package called [`eslint-config-erb-javascript`](https://github.com/electron-react-boilerplate/eslint-config-erb/tree/master/packages/eslint-config-erb-javascript) you can install to replace the existing `eslint-config-erb` which uses TS.
You can try to update the ESLint config with something like this:
```javascript
module.exports = {
  extends: 'erb-javascript',
  rules: {
    // A temporary hack related to IDE not resolving correct package.json
    'import/no-extraneous-dependencies': 'off',
  },
  parserOptions: {
    ecmaVersion: 2020,
    sourceType: 'module',
  },
  settings: {
    'import/resolver': {
      // See https://github.com/benmosher/eslint-plugin-import/issues/1396#issuecomment-575727774 for line below
      node: {},
      webpack: {
        config: require.resolve('./.erb/configs/webpack.config.eslint.js'),
      },
    },
  },
};
```
This is what I guess I did not actually test it. There is probably things to change. Hope this can still help you.

**Comment by zedtux** [comment]
By "official" I was thinking of this project's people but thank you anyway 😉

**Comment by pbreah** [comment]
I have migrated a project 3 times already in less than 2 weeks to different electron boilerplates that seemed to have a lot of stars but at the end of the day are completely broken when you try to package your app. Since this boilerplate is the most up-to-date, I would love to see this boilerplate have the option to enable or disable TS (could be just a different branch, or a script to run, if you want TypeScript in your project). I feel the same as @zedtux that TypeScript is probably beyond the "required" threshold, as some projects you will be required to use just JS.

**Comment by pbreah** [comment]
removing TS is not as straightforward: there is an extension on .eslintrc.js -> extends: 'erb' which uses TS. I went to that repo and copied the extensions under there except the typescript ones. Then disabling that makes the rule 'import/no-extraneous-dependencies' not found. Is this really needed?

After that there's the ./src/menu.ts and ./assets/assets.d.ts that needs to be replaced with JS code.

**Comment by zedtux** [comment]
I'm not sure why you've closed this issue @amilajack, as I don't see any official documentation on how to not use typescript 🤔.
Was a mistake?

**Comment by amilajack** [comment]
https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2778#issuecomment-797804056 should work for migrating from ts to js.

**Comment by zedtux** [comment]
Yeah ... I see, thank you @amilajack 😒

**Comment by amilajack** [comment]
Reopening to track adding documentation

**Comment by zedtux** [comment]
Here we go ... stupid bot game again 👏 .

Someone to create a bot to fight those "stale" bots?

**Comment by zedtux** [comment]
Brillant

**Comment by cklasacrcez** [comment]
Maybe there should be a separate repository/branch for javascript? I don't use really typescript and I would like to have a boilerplate just for javascript (I'm a beginner)

**Comment by epiphaneSpecter** [comment]
I am also looking for a version without typescript, not that I am unfamiliar with typescript and its usefulness. but because sometimes some libraries do not have a type and it is really boring to use them or to put any everywhere

**Comment by cklasacrcez** [comment]
I managed to make a javascript only template, I will upload it soon.

czw., 18 lis 2021 o 22:17 epiphaneSpecter ***@***.***>
napisał(a):

**Comment by MiLaDTechS** [comment]
it would be nice to have an option "--template typescript", or a seprate branch for js, like all other biolerplates
this way you can start things much faster when you just need to make a demo of your idea

**Comment by pramod-bls** [comment]
any update on this?
