### ISSUE TITLE
Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead

### ISSUE THREAD

**Issue by meirrod** [electron-react-boilerplate/electron-react-boilerplate#2926]
Hi,
i'm trying to read a json file to import some settings during the startup. While using yarn build && yarn start the program starts correctly. If i try to compile with electron-builder --win --x64 the error in the title shows up.

That's the config.js file:

```javascript
const file = fs.readFileSync(path.join(RESOURCES_PATH, 'config.json'), 'utf8');

module.exports = {
  config: JSON.parse(file),
};
```
which i import in another js file with:

```javascript
const config = require('./config'); 
```

That's the error:
![image](https://user-images.githubusercontent.com/75636671/125578424-aaed7c6f-24f6-455a-9c25-980f547cef29.png)

If you need more, just ask.
Thanks in advance

**Comment by isasmendiagus** [comment]
In order to compile your app you should run `yarn package` instead of `electron-builder --win --x64`.
`yarn package` will compile for the current OS and Arch.


I'm not an expert, but try to change your config.js for the following:
```javascript
const appConfig = fs.readFileSync(path.join(RESOURCES_PATH, 'config.json'), 'utf8');
export appConfig
```

And import the file with the following:
```javascript
import { appConfig } from ' RELATIVE_PATH_TO_CONFIG.js '
```

Just keep in mind if you have RESOURCES_PATH as a fixed path it will bring you some issues when trying to distribute the app.
