### ISSUE TITLE
Why // Deliberately strip event as it includes `sender`?

### ISSUE THREAD

**Issue by LarryKlugerDS** [electron-react-boilerplate/electron-react-boilerplate#2951]
## Summary

In [preload.js](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/main/src/main/preload.js#L11) the bridged version of ipcRenderer available to the renderer code is changed to strip out the `event` parameter to the event listener function

Current code:
````
        // Deliberately strip event as it includes `sender`
        ipcRenderer.once(channel, (event, ...args) => func(...args));
````

Why is this being done?

**Comment by BenRussert** [comment]
To be as secure as possible, you don't want to expose any electron apis directly in the renderer process. The preload script allows you to wrap only what is needed so that you don't expose any powerful objects like an instance of `ipcRenderer` to client side code.

In this case if the `sender` was another browser window sent directly using `ipcRenderer.sendTo`, the event `sender` returned that would be an instance of `ipcRenderer` that the client side code would now have access to.

[More in the electron docs here](https://www.electronjs.org/docs/latest/tutorial/context-isolation/#security-considerations)
