### ISSUE TITLE
How do I import a CSS file from node_modules?

### ISSUE THREAD

**Issue by developomp** [electron-react-boilerplate/electron-react-boilerplate#3034]
How do I import a CSS file from node_modules?
I've been trying to solve this problem for one whole day trying every combination under the sun and none of them worked for me.

The only thing that was even remotely close to a solution was adding a stylesheet link to cdn in `index.ejs` but I'd like a solution that works offline too.

index.ejs:
```
<link
    async
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/semantic-ui@2/dist/semantic.min.css"
/>
```

Things I've tried (and every combination):

- adding `~` in front of the import path
- using relative path (`../..`)
- adding this to [`webpack.config.base.ts`](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/main/.erb/configs/webpack.config.base.ts):
   ```
   {
       test: /\.css$/,
       loader: "style-loader!css-loader"
   }
   ```
- importing in the TSX file directly with `import 'package/path/to/css.css';`
- adding `@import 'package/path/to/css.css';` to a CSS file and importing it

Related issues:

- #352
- #806
- #1087
- https://github.com/parcel-bundler/parcel/issues/1868

How to reproduce the issue:
- clone the erb repo
- install the [`semantic-ui-css`](https://www.npmjs.com/package/semantic-ui-css) package
- try to import `semantic-ui-css/semantic.min.css`

**Comment by developomp** [comment]
This is driving me crazy

**Comment by kbrisso** [comment]
Check this thread out below. I have not tried this yet but will be doing so soon. 

https://stackoverflow.com/questions/49518277/import-css-from-node-modules-in-webpack

**Comment by amilajack** [comment]
Here's an example of integrating tailwind, which requires importing tailwind from node_modules
https://github.com/amilajack/erb-tailwind-example/commit/5962bb60d4efb48d20a77d061f8bd9b3dad374b4

**Comment by developomp** [comment]
> Here's an example of integrating tailwind, which requires importing tailwind from node_modules [amilajack/erb-tailwind-example@5962bb6](https://github.com/amilajack/erb-tailwind-example/commit/5962bb60d4efb48d20a77d061f8bd9b3dad374b4)

This seemed promising but adding CSS loaders to `module.rules` in webpack config didn't work :(

No matter what I do as soon as I add the line `import "semantic-ui-css/semantic.min.css"` I get a `Cannot GET /index.html` error.

**Comment by UserJHansen** [comment]
In your `app.css` you should be able to use: 

`
@import '~semantic-ui-css';`

**Comment by developomp** [comment]
> In your `app.css` you should be able to use:
> 
> ` @import '~semantic-ui-css';`

That's not even a CSS stylesheet.

**Comment by UserJHansen** [comment]
Have you tried it? It works for Bootstrap

**Comment by developomp** [comment]
Yes, and it doesn't work.

**Comment by amilajack** [comment]
This is a working example of ERB + bootstrap https://github.com/kbrisso/erb-bootstrap-ipc

**Comment by UserJHansen** [comment]
> This is a working example of ERB + bootstrap https://github.com/kbrisso/erb-bootstrap-ipc

Sorry but we are looking for a solution for semantic ui

**Comment by UserJHansen** [comment]
I just looked through the errors and it looks like it is a problem with importing fonts.

**Comment by kbrisso** [comment]
@developomp  I tried to replicate your issue but I could not install Semantic because of a Gulp issue. What I did is download the current build https://github.com/Semantic-Org/Semantic-UI-CSS/archive/master.zip.  I unpacked it in the node_modules folder and then added the dependency to my package file. I wasn't able to use the "~" import but I was able to add this to the App.tsx 
![image](https://user-images.githubusercontent.com/15221353/141169104-d2cf1bda-7fce-4e26-b5bc-0e5db5a34771.png)

It built fine but then when I ran it I encountered this error. 
![image](https://user-images.githubusercontent.com/15221353/141168767-79810fd9-4d97-4ce0-ac43-831803a1b145.png)

I found this post 
https://github.com/Semantic-Org/Semantic-UI-React/issues/4227

I removed the semicolon from min CSS and then I ran it again and it worked.
![image](https://user-images.githubusercontent.com/15221353/141169361-925494a6-d32a-4b0f-9600-a39bc8b3fc2d.png)

It seems to work this way, let me know if this helps.

**Comment by UserJHansen** [comment]
Shame we can't fix the issue here

**Comment by developomp** [comment]
Thank you so much @kbrisso for taking a deep look into it.
Removing one semicolon from the double does fix the issue.
I was about to open an issue in their repo but the last commit is from 2018 :(

I ended up writing a script for postinstall that replaces double semicolons from `semantic-ui-css/semantic.css` and `semantic-ui-css/semantic.min.css`.
