### ISSUE TITLE
Electron store returning undefined

### ISSUE THREAD

**Issue by zaynekomichi** [electron-react-boilerplate/electron-react-boilerplate#3069]
Trying to make electron store return a value
`<button onClick={() => { window.electron.store.set("foo","b");
               console.log(window.electron.store.get("foo")); }}>
Click Me</button>`
Instead getting undefined in console when I request the data
I have already setup the other files preload,main and app->below
![Screenshot (17)](https://user-images.githubusercontent.com/54587124/146637143-9ce2152f-6050-45d4-8bb3-35d6131770fb.png)
![Screenshot (18)](https://user-images.githubusercontent.com/54587124/146637150-4f481526-2f57-474b-bc6b-c29f3bff6473.png)
![Screenshot (19)](https://user-images.githubusercontent.com/54587124/146637151-7a5b6201-46ee-4763-a69f-819d93282806.png)

**Comment by kbrisso** [comment]
Please to take a look at this

https://electron-react-boilerplate.js.org/docs/electron-store

Take a look at how I added the IPC render type file in this project below - global.d.ts. In order to use IPC renderer in the App.tsx you need a type file with an interface. Let me know if this helps. This will allow you to use the methods in preload.js.

https://github.com/kbrisso/erb-bootstrap-ipc

Hope this helps.

**Comment by zaynekomichi** [comment]
Thank you for the example it worked noticed I had left out the interface part
