### ISSUE TITLE
How to pass React click events to electron?

### ISSUE THREAD

**Issue by mgscreativa** [electron-react-boilerplate/electron-react-boilerplate#3097]
## Summary
Hi! just downloaded and started to play around with the boilerplate but problems raised when I tried to create a chomeless transparent windows, so I created a little React TitleBar component, but I don't know how can I send the widnow minimize, maximize and close commands. I know that some sort of work must be done with the ipcRenderer but I can't even import that into my React component

As for testing, downloaded ERB 4.4.0 and tried to import ipcRenderer in the React App component, this is the resulting code of my React component, and I'm attaching the error that I get in the console.

```
import { Component } from 'react';
import { ipcRenderer } from 'electron';

import { MemoryRouter as Router, Switch, Route } from 'react-router-dom';

import icon from '../../assets/icon.svg';
import './App.css';

class Hello extends Component {
  componentDidMount() {
    console.log(ipcRenderer);
  }

  render() {
    return (
      <div>
        <div className="Hello">
          <img width="200px" alt="icon" src={icon} />
        </div>
        <h1>electron-react-boilerplate</h1>
        <div className="Hello">
          <a
            href="https://electron-react-boilerplate.js.org/"
            target="_blank"
            rel="noreferrer"
          >
            <button type="button">
              <span role="img" aria-label="books">
                📚
              </span>
              Read our docs
            </button>
          </a>
          <a
            href="https://github.com/sponsors/electron-react-boilerplate"
            target="_blank"
            rel="noreferrer"
          >
            <button type="button">
              <span role="img" aria-label="books">
                🙏
              </span>
              Donate
            </button>
          </a>
        </div>
      </div>
    );
  };
}

export default function App() {
  return (
    <Router>
      <Switch>
        <Route path="/" component={Hello} />
      </Switch>
    </Router>
  );
}
```

```
ERROR in ./node_modules/electron/index.js 1:11-24
Module not found: Error: Can't resolve 'fs' in '/home/martinb/Escritorio/electron-react-boilerplate-4.4.0/node_modules/electron'
 @ ./src/renderer/App.tsx 10:19-38
 @ ./src/renderer/index.tsx 10:30-46

ERROR in ./node_modules/electron/index.js 2:13-28
Module not found: Error: Can't resolve 'path' in '/home/martinb/Escritorio/electron-react-boilerplate-4.4.0/node_modules/electron'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
 @ ./src/renderer/App.tsx 10:19-38
 @ ./src/renderer/index.tsx 10:30-46

webpack compiled with 2 errors
Not rewriting GET /index.html because the path includes a dot (.) character.
```

**Comment by sensible-s** [comment]
So a couple of things. 

If you want to import and call `ipcRenderer` directly anywhere in the renderer folder, there are a bunch of steps you need to take, basically enabling node integration.  

So this line is probably breaking your code to start with, unless you have taken those steps:
```import { ipcRenderer } from 'electron';```

Otherwise your error message is saying that it can't resolve fs, which is a node module, and subject to the same problem. Check that you aren't importing `fs` anywhere in the renderer folder.

Lastly, to your original question. How to pass click events to electron. You use the context bridge, which is what this boilerplate is set up with currently. https://www.electronjs.org/docs/latest/api/context-bridge

Add a method in the context bridge (preload.js). Ex:
```
myPing(messageVar) {
  ipcRenderer.send('ipc-example', messageVar);
},
```

You access the context bridge through the window object. So to actually send the message, you can write this anywhere in one of your react components:
`window.electron.ipcRenderer.myPing("I am 97% asleep");`

Currently nothing will happen, because nothing in the main electron process is listening for this channel (or doing anything with it). So add to the main process too:
```
ipcMain.on('ipc-example', async (event, messageVar: string) => {
  console.log(messageVar);
});
// output: "I am 97% asleep"
```

**Comment by mgscreativa** [comment]
Thanks! @sensible-s got this sorted out... Attaching my demo code which implements chromeless transparent window with custom title bar

[electron-react-boilerplate.zip](https://github.com/electron-react-boilerplate/electron-react-boilerplate/files/7823055/electron-react-boilerplate.zip)

**Comment by mgscreativa** [comment]
Just wondering, I can't listen to 
```
  mainWindow.on('maximize', () => console.log('maximize event'));
  mainWindow.on('unmaximize', () => console.log('unmaximize event'));
```
Is that related to have a chromeless transparent window?

**Comment by sensible-s** [comment]
No idea off the top of my head sorry.
