### ISSUE TITLE
White screen in desktop app build

### ISSUE THREAD

**Issue by kartset** [electron-react-boilerplate/electron-react-boilerplate#3156]
## Prerequisites

- [X] Using npm
- [X] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [X] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [X] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [X] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

Expected Behavior was the proper working of the output app.

## Current Behavior

Whenever I am generating a desktop app using `npm run package` and running it the app loads and shows a blank white screen.

This is the screenshot of the console output of `DEBUG_PROD=true npm run build && npm start` command 
 ![Screenshot from 2022-03-05 16-22-05](https://user-images.githubusercontent.com/30878021/156880119-0012a497-c0fc-476f-8831-2baac8520d60.png)

Following is the screenshot of the output of the `npm run package`:
![Screenshot from 2022-03-05 17-11-05](https://user-images.githubusercontent.com/30878021/156881462-72f32b00-c74f-4fed-8bb0-0c0ef8ca235d.png)

## Steps to Reproduce

1. Following is my package.json file. For reproducing the bug you can download a clean repo of this template and replace this package.json with the template's one and install the packages and write a simple program using installed libraries. (I tried this but could not figure out the problem). To see the package.json file, [click here](https://gist.github.com/kartset/1d3a39d8771297838701a22e4010d2b3).

## Context

We are trying to build a prototype for an idea of a desktop app using electron-react-boilerplate. We installed a lot of other libraries to use with the electron-react-boilerplate such as redux-toolkit or @elastic/eui and apisauce and lodash etc. Earlier we built a prototype with the electron-boilerplate and we were able to generate a perfect build/package as a desktop app. So when we started building the prototype with this boilerplate instead of checking whether we are able to generate a perfect build at every step we just kept writing the code for the UI Part and when we had to test the complete app as a desktop app we tried to produce a desktop app using `npm run package`. We tried so many things but we couldn't and this issue is platform-independent we have tried to generate a build on Linux as well as on Windows. We are getting this issue only when we generate a desktop app as for the normal web build everything is working fine. There was one change that I did to the electron-react-boilerplate code that is in the src/main/main.ts file on line 84.
Earlier it was `  mainWindow.loadURL(resolveHtmlPath('index.html'));` and now it is `  mainWindow.loadURL(resolveHtmlPath('/'));` as I was using the route to show the page heading so whenever the app used to load so on the homepage instead of 'Profile' as the heading it used to come index.html. 

## Your Environment

OS Name:  Ubuntu 20.04.3 LTS
OS Type: 64-bit
GNOME Version: 3.36.8
Windowing System: X11

- Node version: 16.13.0
- electron-react-boilerplate version or branch: main branch cloned after Dec 2021
- Operating System and version: Ubuntu 20.04.3 LTS
- Link to your project: the repository is private as of now and I can share if I could discuss the problem for the resolution with a developer on the electron-react-boilerplate instead of sharing the link publicly here.

**Comment by XjSv** [comment]
I have the same problem. I think as you mentioned that the issue is related to the `resolveHtmlPath` function in utils.ts.

One improvement that could help is to change the return from:
`return 'file://${path.resolve(__dirname, '../renderer/', htmlFileName)}';`
to:
`return 'file://${path.resolve(__dirname, '..', '/renderer/', htmlFileName)}';`
This seems to resolve the path better, especially on Windows. 

But still on Windows I am having the issue you described.
It's funny because I went through the exact same process as you. Developed for about a week without ever thinking to package it. I went through and had to check each and every dependency and finally after all that I was presented with a blank page. LOL I had even change the same line as you did `mainWindow.loadURL(resolveHtmlPath('/'));`

**Comment by XjSv** [comment]
I think I might have resolved the issue, at least for myself. Maybe this will help you too.
In `src\main\util.ts` I changed the return for the production build from:

`return 'file://${path.resolve(__dirname, '../renderer/', htmlFileName)}';`
To:
`return 'file://${path.join(__dirname, '..', '/renderer/', htmlFileName)}';`

The logic here is that `path.resolve` is designed to resolve absolute paths, but because `__dirname` is already an absolute path we will end up with the same result.

For me this resolved to the correct path `file:///M:/Projects/my-project/release/build/win-unpacked/resources/app.asar/dist/renderer/index.html`

When using `path.resolve` the path ended up being `file:///M:/renderer/index.html`

**Comment by XjSv** [comment]
There might be something else causing the problem because if you clone the repo and package it, there is no issue.

**Comment by cosoc** [comment]
的确存在这个bug,应该是打包造成的，当我打开包时依然无法显示内容！

**Comment by cosoc** [comment]
我已经解决，因为react-router-dom v6 版本中路由问题我是加

```
<Router>
          <Routes>
              <Route path='/*' element={<Home/>}/>
          </Routes>
      </Router>
```

**Comment by TrumanDu** [comment]
the same issue. how to fix?
[code](https://github.com/TrumanDu/TDA)

**Comment by kartset** [comment]
@TrumanDu on line no. 103 try changing  mainWindow.loadURL(resolveHtmlPath('')); to mainWindow.loadURL(resolveHtmlPath('index.html'));

**Comment by uwemneku** [comment]
If you're using ```react-router-dom``` and you're here because you see a blank screen in production but it works fine in development. What worked for me was  wrapping the app with ```HashRouter``` instead of  ```BrowserRouter```
