### ISSUE TITLE
how to exclude packages from the webpack build

### ISSUE THREAD

**Issue by Traineratwot** [electron-react-boilerplate/electron-react-boilerplate#3268]
## Summary

Hello, I don't know webpack well, and I get errors when building or starting my project

The project is going and working fine, getaction crashes with an error :(

I use [primereact](https://www.primefaces.org/primereact/)

[my project(still in development)](https://github.com/Traineratwot/project-manager)

Please tell me how to exclude these 2 packages from the dll assembly?

```
> postinstall
> ts-node .erb/scripts/check-native-dep.js && electron-builder install-app-deps && cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.ts
  • electron-builder  version=23.0.3
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=linux arch=x64 appDir=/home/runner/work/project-manager/project-manager/release/app
ERROR in dll rendererrenderer[12]
Module not found: Error: Can't resolve 'primeicons' in '/home/runner/work/project-manager/project-manager'
ERROR in dll rendererrenderer[13]
Module not found: Error: Can't resolve 'primereact' in '/home/runner/work/project-manager/project-manager'
```

**Comment by Evilscaught** [comment]
Hi Traineratwot,

A few months ago I ran into the same problem and suffered for probably a whole week trying to figure out what needed to be done. There are certain things which need to be excluded from Webpack when building the application.  Here is how I solved the issue on your project:

# Step 1
First,  you need to move your package dependency `"@types/js-search": "^1.4.0",` to `devDependencies`. 
Start by uninstalling it;
```bash
   npm uninstall @types/js-search
```
and re-installing it:
```bash
   npm install --save-dev @types/js-search
```
This will resolve the first DLL error you've been getting in the postinstall script.
```bash
ERROR in dll renderer renderer[3]
Module not found: Error: Can't resolve '@types/js-search' in '/Users/evilscaught/Documents/e-boilerplate/project-manager'
```

`@types` belong in developer dependencies because Typescript is only used to type check in a development environment, once you've built and released your application it is compiled to just regular JavaScript. Trying to compile it through Webpack will give you a bad time.

# Step 2 

In your project code editor, open the following file:
`.erb/configs/webpack.config.renderer.dev.dll.ts`
and add the following strings to the `externals` array on `LINE 26`
`'primeicons', 'primereact'`

The changes made should look like this: 
```diff
...

const configuration: webpack.Configuration = {
  context: webpackPaths.rootPath,

  devtool: 'eval',

  mode: 'development',

  target: 'electron-renderer',

- externals: ['fsevents', 'crypto-browserify' ],
+ externals: ['fsevents', 'crypto-browserify', 'primeicons', 'primereact'],
...

```

Then again, in your `.erb/configs/webpack.config.renderer.prod.ts` file, add `externals` to `LINE 26`
`externals: [ 'primeicons', 'primereact' ],`

The changes made should look like this:
```diff
...
checkNodeEnv('production');
deleteSourceMaps();

const configuration: webpack.Configuration = {
  devtool: 'source-map',

  mode: 'production',

  target: ['web', 'electron-renderer'],

+  externals: [ 'primeicons', 'primereact' ],
...
```

This pretty much tells Webpack to ignore these dependencies and simply pass them straight to your project build. 
Now that you've done that, the other two DLL errors should be resolved, and you can test this yourself by running:

`npm run postinstall`
then
`npm run build`
then
`npm run package`
And start the executable of your built application on your computer

**Comment by Traineratwot** [comment]
Thank you very much 👍
