### ISSUE TITLE
Source code protection

### ISSUE THREAD

**Issue by piedpie** [electron-react-boilerplate/electron-react-boilerplate#3405]
Some boilerplates out there seem to be using `bytenode-webpack-plugin` for source code protection.
Why is this plugin not included it in the ERB boilerplate?

**Comment by jjj201200** [comment]
You can use `bytenode-webpack-plugin` in your project. I’m using it, but debugging a issue in renderer page.

**Comment by amilajack** [comment]
this will likely not be added to erb since it complicates things and isn't very standard

**Comment by piedpie** [comment]
@jjj201200 , When I add the plugin I get errors after packaging - `module not found`. 
I believe we only have to add plugin in the webpack config file.
Or is there any other change required?

**Comment by jjj201200** [comment]
@piedpie You should must set `nodeIntegration: true` and `contextIsolation: false` for your BrowserWindow config.

Because it need to use node module in your renderer process, especially the require module.

So may be this makes us can not use `contextBridge` in preload file.

The problem I encountered is [here](https://github.com/herberttn/bytenode-webpack-plugin/issues/21), but i have found a less elegant way to resolve it, just add the follow code in index.html:

```javascript
if (process.env.NODE_ENV !== 'development') {
    require.extensions[".css"] = () => {
      return;
    };
    require('./main.compiled.jsc');
  }
```

If I have time afterwards, I will spend some time debugging this problem.
