### ISSUE TITLE
Have some problems "npm run package" in mac

### ISSUE THREAD

**Issue by mithang** [electron-react-boilerplate/electron-react-boilerplate#3515]
I have some problems when I deploy Mac by command: npm run package.
Please help me.
<img width="1215" alt="Screenshot 2023-08-09 at 18 00 47" src="https://github.com/electron-react-boilerplate/electron-react-boilerplate/assets/20384021/98847095-1b1d-47d9-a4f2-230316d20df1">

**Comment by mithang** [comment]
Urgent, Please help me

**Comment by thoralt** [comment]
This does not seem to be an error in electron-react-boilerplate. The error message clearly states ´CSSMERR_TP_CERT_REVOKED´ which looks like the certificate you're trying to use is no longer valid (has been revoked). Does this also fail if you execute the offending command ´codesign --verify --deep --strict ... ... /ElectronReact.app` manually? Did it work before?

P.S.: Don't use screenshots for terminal output unless absolutely necessary. Everyone trying to help you needs to re-type the texts when using it instead of simply using copy/paste.

**Comment by mithang** [comment]
> Tôi gặp một số vấn đề khi triển khai Mac bằng lệnh: npm run package. Làm ơn giúp tôi. <img alt="Ảnh chụp màn hình 2023-08-09 lúc 18 00 47" width="1215" src="https://user-images.githubusercontent.com/20384021/259385718-98847095-1b1d-47d9-a4f2-230316d20df1.png">
