### ISSUE TITLE
How to write file with electron?

### ISSUE THREAD

**Issue by Curiosit** [electron-react-boilerplate/electron-react-boilerplate#3518]
## Summary

I am trying to write a JSON file, however I have problems, as I cannot use require fs

I tried with this function in App.jsx:

`const writeFile = (filename, data) => {
    var fs = require("fs");
    read_file = function(path){
      return fs.readFileSync(path, 'utf8');
    } 
    onst output = data;
    const path = "/output"+filename+".json";
    write_file = function(path, output){
      fs.writeFileSync(path, output);
    } 
    
    
  }`

I get error:
`Module not found: Error: Can't resolve 'fs'`

**Comment by praveen-zluri** [comment]
I tried to achieve the same thing a month ago and found out that we cannot use node modules directly in `App.tsx` because electron's `renderer` process doesn't have access to these native Node modules. So, what you need to do is, enable `nodeIntegration` to `true`

```
webPreferences: {
   nodeIntegration: true
},
```

Note that you can use native modules in only `main process`.

And if you want to use node modules in the renderer process, you need to handled from the `webpack config` end:

`https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/main/.erb/configs/webpack.config.renderer.dev.ts` and add the js files that use node modules under the entry point.

**Please read these for more info:**

https://stackoverflow.com/questions/68279632/how-to-use-node-modules-in-electron-react-app
https://www.codiga.io/blog/build-electron-typescript-react-app/

**Comment by Curiosit** [comment]
Thanks! I solved this differently, according to this article:
https://www.electronjs.org/docs/latest/tutorial/ipc
